In [32]:
import pandas as pd
import requests
from urllib.parse import quote

In [33]:
# ================= CONFIG =================

TENANT_ID = "62a0b673-6bc5-43fb-8ab0-37fb99dbcec9"
COMPANY = "DDCL"

CLIENT_ID = "YOUR_CLIENT_ID"
CLIENT_SECRET = "YOUR_CLIENT_SECRET"


API_URL = f"https://api.businesscentral.dynamics.com/v2.0/{TENANT_ID}/UAT/ODataV4/Company('{COMPANY}')/VendorListAPI"

TOKEN_URL = f"https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/token"

In [ ]:
# ================= GET ACCESS TOKEN =================

import os

TENANT_ID = "62a0b673-6bc5-43fb-8ab0-37fb99dbcec9"
COMPANY = "DDCL"

CLIENT_ID = os.environ["CLIENT_ID"]
CLIENT_SECRET = os.environ["CLIENT_SECRET"]

API_URL = f"https://api.businesscentral.dynamics.com/v2.0/{TENANT_ID}/UAT/ODataV4/Company('{COMPANY}')/VendorListAPI"

TOKEN_URL = f"https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/token"

EXCEL_FILE = r"E:\Local_Pipelines\Vendors.xlsx"

def get_token():
    payload = {
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
        "scope": "https://api.businesscentral.dynamics.com/.default",
        "grant_type": "client_credentials"
    }

    r = requests.post(TOKEN_URL, data=payload)
    r.raise_for_status()

In [35]:
token

'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlBjWDk4R1g0MjBUMVg2c0JEa3poUW1xZ3dNVSIsImtpZCI6IlBjWDk4R1g0MjBUMVg2c0JEa3poUW1xZ3dNVSJ9.eyJhdWQiOiJodHRwczovL2FwaS5idXNpbmVzc2NlbnRyYWwuZHluYW1pY3MuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNjJhMGI2NzMtNmJjNS00M2ZiLThhYjAtMzdmYjk5ZGJjZWM5LyIsImlhdCI6MTc3MDIwNTg5MywibmJmIjoxNzcwMjA1ODkzLCJleHAiOjE3NzAyMDk3OTMsImFpbyI6ImsyWmdZUGp4NnRVT3FZeUhWcHNEVXFyTldyMG1BZ0E9IiwiYXBwaWQiOiI5OGFiODNkMi0zNWNiLTRmMzctYmI5Ny1hMTRiZDkxNzI2ZDQiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC82MmEwYjY3My02YmM1LTQzZmItOGFiMC0zN2ZiOTlkYmNlYzkvIiwiaWR0eXAiOiJhcHAiLCJvaWQiOiIyZWY0ZWFhNS03Zjk2LTRiYzEtOWRlNi01MjIwMjY0NTI0ZTUiLCJyaCI6IjEuQVQwQWM3YWdZc1ZyLTBPS3NEZjdtZHZPeVQzdmJabHNzMU5CaGdlbV9Ud0J1SjhBQUFBOUFBLiIsInJvbGVzIjpbIkF1dG9tYXRpb24uUmVhZFdyaXRlLkFsbCIsImFwcF9hY2Nlc3MiLCJBZG1pbkNlbnRlci5SZWFkV3JpdGUuQWxsIiwiQVBJLlJlYWRXcml0ZS5BbGwiXSwic3ViIjoiMmVmNGVhYTUtN2Y5Ni00YmMxLTlkZTYtNTIyMDI2NDUyNGU1IiwidGlkIjoiNjJhMGI2NzMtNmJjNS00M2ZiLThhYjAtMzdmYjk5ZGJjZWM5IiwidXRpIjoiNzVuTUxGdGVYVUtiaUI0RGpmc2ZBQSIsInZlciI6IjEuMCIsInhtc19hY3RfZmN0IjoiOSAzIiwieG1zX2Z0ZCI6Ii1tLXdVTllZekh6N3BHeU14ZlVpWWJxc1VIWEQ0LXoxd0c1eWRWdl9udXdCWVhOcFlYTnZkWFJvWldGemRDMWtjMjF6IiwieG1zX2lkcmVsIjoiMjYgNyIsInhtc19yZCI6IjAuNDJMbFlCSml0QlVTNFdBWEVyQ2RWT0lvUEctWlM3LWNPU1B2MHVVYmdhS2NRZ0t4WEp5WnYxN09jZC1UZGlQbDV0VTZMNkFvQjFEdC05eVpPWnVESGR2WWxfMjFZZHd4SHlqS0xTUnc5ZTJzazB1ZnYtenlkenFzNmIzbjcyTUEiLCJ4bXNfc3ViX2ZjdCI6IjMgOSJ9.c4pPrEKrF_NuyKOa0Q9tdMTIC-l0RSgmWDsFgX33YyBZAO2sFShDhU81l0StFdW9G_xV7ddssVzO5OA3qRKLKjJsvfqnHtZfIeNCymsq1p6YCxBZK3T3aPTLgio6cX69_Tock2-N7oPSVgloPgfkjK4qdi7nQG2nQXHhuhQXoJ59Qfz68MVPAyBtWI4ALPO4M0yy4kZSgrQmGdK3WpNQ3kG12YfMPmdHxsu5sFbYlE6fVqilvncSVEJt1aurmNr7EUH7-SYdBMy8jsDL1h648miQlCQan94dGVpjzx2wvVq5ayuknLojYB6SPepYkbZ9HpUmJL7Jl3E9sC7WOfsuFQ'

In [23]:
# EXCEL_FILE = r"E:\Local_Pipelines\Vendors.xlsx"
df = pd.read_excel(EXCEL_FILE)
df

,Old_Vendor_ID,name,name2,Balance_LCY,address,address2,city,stateID,districtID,VendordeliveryCondition,...,Vendor_Posting_Group,Post_Code,Population,pANNo,P_A_N_Status,GST_Registration_No,GST_Vendor_Type,Global_Dimension_1_Filter,Global_Dimension_2_Filter,Currency_Filter
0,NaN,Sunita,Bavaskar,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Jyoti,Devi,0,NaN,NaN,NaN,1,624,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nirada,Deka,0,NaN,NaN,NaN,18,283,NaN,...,NaN,NaN,NaN,CKIPD6812R,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Nikumoni,saikia,0,NaN,NaN,NaN,18,288,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Momi,Muktiar,0,NaN,NaN,NaN,18,297,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Dulal,Borah,0,NaN,NaN,NaN,18,288,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Rama,Devi,0,NaN,NaN,NaN,2,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Urmila,Nag,0,NaN,NaN,NaN,18,286,NaN,...,NaN,NaN,NaN,CZAPN3954M,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Darshana,Girnale,0,NaN,NaN,NaN,27,468,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Tanisha,Patel,0,NaN,NaN,NaN,27,487,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,RAHUL GOLE,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Anita,Devi,0,NaN,NaN,NaN,9,187,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Rutuja,Gudadhe,0,NaN,NaN,NaN,27,468,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Saruwar,Jahan,0,NaN,NaN,NaN,18,301,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Mahaboob,Ansari,0,NaN,NaN,NaN,9,123,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Khaleda,Molla,0,NaN,NaN,NaN,19,304,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Nilam,Devi,0,NaN,NaN,NaN,20,324,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Usha,Devi,0,NaN,NaN,NaN,9,159,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,Sumitra Devi,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Usha,Devi,0,NaN,NaN,NaN,9,159,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,Sabitri Ray,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,Vishakha Rahul manwar,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,AJIT,Das,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Aysha Siddika,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Parveen,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,Sugambar,Yadav,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,Mahesh Kumar Kalita,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Amrika bai,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Mrinmoyee Narjaree,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,Shital pankaj madhwakar,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Raigarh,Cluster,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Subol Biswas,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,Rinku Das,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,Pranami Kaushik,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,Rajani,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,Abhay Pratap Singh,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,Pratima Sha Gupta,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,Raj Kumar Gupta,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,Nomita Goswami Mahanta,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,Jayanta Kumar Nath,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,DHARMENDRA,KUMAR,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,Dalia Das,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,Shyamali Mandal,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,BISHWAJIT BOBORUAH,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,Bornali Gogoi,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,Madhuri ravindra wankhede,NaN,0,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Generate Vendor Code

In [ ]:
headers = {
    "Authorization": f"Bearer {token}",
    "Content-Type": "application/json",
    "If-Match": "*"
}

success = 0
failed = 0

for index, row in df.iterrows():

    body = {
        "Old_Vendor_ID": "",
        "name": str(row["name"]),
        "name2": "",
        "Balance_LCY": 0,
        "address": str(row["address"]),
        "address2": "",
        "city": "",
        "stateID": int(row["stateID"]),
        "districtID": int(row["districtID"]),
        "VendordeliveryCondition": " ",
        "PaymentTerms": " ",
        "mobilePhoneNo": str(row["mobilePhoneNo"]),
        "whatsAppNo": str(row["whatsAppNo"]),
        "eMail": "", #str(row["eMail"]),
        "fullAddress": str(row["address"]),
        "BankName": "",
        "bankAccountName": str(row["bankAccountName"]),
        "bankAccountNo": str(row["bankAccountNo"]),
        "bankAccountIFSC": str(row["bankAccountIFSC"]),
        "cspCode": "",
        "Vendor_Type": "SCM Vendor",
        "Ledger_Type": "Expansion",
        "Vendor_Posting_Group": "SC_SCM",
        "Post_Code": "",
        "Population": " ",
        "pANNo": str(row["pANNo"]),
        "P_A_N_Status": " ",
        "GST_Registration_No": "",
        "GST_Vendor_Type": " ",
        "Global_Dimension_1_Filter": "",
        "Global_Dimension_2_Filter": "",
        "Currency_Filter": ""
    }

    response = requests.post(API_URL, headers=headers, json=body)

    if response.status_code in [200, 201]:
        dd = response.json()
        vendor_code = dd['no']
        df.at[index, "VendorCode"] = vendor_code
        df.at[index, "Status"] = "SUCCESS"

        print(f"✅ {row['name']} → {vendor_code}")
        print(f"✅ Row {index+1} created : {row['name']}")
        success += 1
    else:
        print(f"❌ Row {index+1} failed : {row['name']}")
        print(response.text)
        failed += 1

print("\n========= SUMMARY =========")
print("Success:", success)
print("Failed :", failed)



for index, row in df.iterrows():

    name = str(row["name"]).strip()
    mobile = str(row["mobilePhoneNo"]).strip()

    # Filter by Name + Mobile
    # url = GET_VENDOR_URL + f"?$filter=name eq '{name}' and mobilePhoneNo eq '{mobile}'"

    # r = requests.get(url, headers=headers)

    if r.status_code == 200:
        result = r.json().get("value", [])

        if result:
            vendor_code = result[0]["no"]
            df.at[index, "VendorCode"] = vendor_code
            print(f"✅ Found: {name} → {vendor_code}")
        else:
            print(f"⚠ Not found: {name}")

    else:
        print(f"❌ Error fetching {name}")

# ---------------- SAVE ----------------

df.to_excel("Vendors_With_Codes.xlsx", index=False)

print("\nDone. File created: Vendors_With_Codes.xlsx")

❌ Row 1 failed : Sunita
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  f9b2b96c-65ab-421d-b12e-7bb0ee41c7e0."}}
✅ Row 2 created : Jyoti
✅ Row 3 created : Nirada
✅ Row 4 created : Nikumoni
✅ Row 5 created : Momi
✅ Row 6 created : Dulal
✅ Row 7 created : Rama
✅ Row 8 created : Urmila
✅ Row 9 created : Darshana
✅ Row 10 created : Tanisha
❌ Row 11 failed : RAHUL GOLE
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  5a56e8ff-61aa-4c2f-ab30-197c02722abb."}}
✅ Row 12 created : Anita
✅ Row 13 created : Rutuja
✅ Row 14 created : Saruwar
✅ Row 15 created : Mahaboob
✅ Row 16 created : Khaleda
✅ Row 17 created : Nilam
✅ Row 18 created : Usha
❌ Row 19 failed : Sumitra Devi
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  11b53bea-d492-49d3-99f8-ec14ebb3d0ea."}}
✅ Row 20 created : Usha
❌ Row 21 failed : Sabitri Ray
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  8462721e-74e0-4777-ab6a-9632379cf146."}}
❌ Row 22 failed : Vishakha Rahul manwar
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  dc8c0868-d0c1-49ef-81a8-f27672b7fb39."}}
❌ Row 23 failed : AJIT
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  bb7aae10-cf03-4a8b-8e69-71737ef8016d."}}
❌ Row 24 failed : Aysha Siddika
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  d92e7a57-0e1c-4cb3-88f0-6d40ed3fca40."}}
❌ Row 25 failed : Parveen
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  70c3f813-829c-4c04-a639-e4c634ac63c2."}}
❌ Row 26 failed : Sugambar
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  c7009391-69e1-4da9-9dd2-9c7afc8413c0."}}
❌ Row 27 failed : Mahesh Kumar Kalita
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  b970a3e8-42ec-4304-af6d-231a81e25457."}}
❌ Row 28 failed : Amrika bai
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  f209e9b9-e2b1-4a11-a69b-d9b8db7f1e15."}}
❌ Row 29 failed : Mrinmoyee Narjaree
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  278873d8-febb-44f3-a8ef-bb542dcdc76c."}}
❌ Row 30 failed : Shital pankaj madhwakar
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  944bd14f-9b1c-4ff7-8e32-d7bba8508952."}}
❌ Row 31 failed : Raigarh
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  c878d0a1-175c-4d2c-bdaf-9bca781cec47."}}
❌ Row 32 failed : Subol Biswas
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  ade3f7b3-d343-440a-8a66-3ffabb288118."}}
❌ Row 33 failed : Rinku Das
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  27cc3275-85ba-43f6-8051-5b74597b4757."}}
❌ Row 34 failed : Pranami Kaushik
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  eeaa478d-eef6-4962-9328-d63abd7edca5."}}
❌ Row 35 failed : Rajani
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  865918d9-7ca4-42e1-8b6a-17ab4a30e335."}}
❌ Row 36 failed : Abhay Pratap Singh
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  ee1ae744-06b2-4796-90ce-77eeeeeece56."}}
❌ Row 37 failed : Pratima Sha Gupta
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  60f5b4c2-3050-4af7-92bd-f7973a17b55e."}}
❌ Row 38 failed : Raj Kumar Gupta
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  c44ed31b-1e16-4249-b912-27ea3c7fccfa."}}
❌ Row 39 failed : Nomita Goswami Mahanta
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  54edd0c4-e254-4a0d-8624-e31f6013fdda."}}
❌ Row 40 failed : Jayanta Kumar Nath
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  42773037-2345-4571-9c1a-3a79ae7abfd1."}}
❌ Row 41 failed : DHARMENDRA
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  8c0a1459-6416-44f3-af4e-3e0ce1a1c140."}}
❌ Row 42 failed : Dalia Das
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  1dd8038e-b209-4c79-babd-abf84a2ae540."}}
❌ Row 43 failed : Shyamali Mandal
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  fd793022-0352-400f-9844-e17c67210b92."}}
❌ Row 44 failed : BISHWAJIT BOBORUAH
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  2533c435-3063-47c9-a934-8a35c3357933."}}
❌ Row 45 failed : Bornali Gogoi
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  2189c7cf-2e98-4459-8127-cdcaf484a3a2."}}
❌ Row 46 failed : Madhuri ravindra wankhede
{"error":{"code":"Application_DialogException","message":"State ID must have a value  CorrelationId:  98ba9f7e-a08d-4ccd-ab79-e6220f514aa3."}}

========= SUMMARY =========
Success: 17
Failed : 29

In [ ]:
df.to_excel("Vendors_Result.xlsx", index=False)

# GET Vendor Code

In [37]:
# p0d.read_excel(EXCEL_FILE)
df = df[df['stateID'] != 0]
df

,Old_Vendor_ID,name,name2,Balance_LCY,address,address2,city,stateID,districtID,VendordeliveryCondition,...,Post_Code,Population,pANNo,P_A_N_Status,GST_Registration_No,GST_Vendor_Type,Global_Dimension_1_Filter,Global_Dimension_2_Filter,Currency_Filter,VendorCode
1,NaN,Jyoti,Devi,0,NaN,NaN,NaN,1,624,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,NaN,Nirada,Deka,0,NaN,NaN,NaN,18,283,NaN,...,NaN,NaN,CKIPD6812R,NaN,NaN,NaN,NaN,NaN,NaN,
3,NaN,Nikumoni,saikia,0,NaN,NaN,NaN,18,288,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,NaN,Momi,Muktiar,0,NaN,NaN,NaN,18,297,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,NaN,Dulal,Borah,0,NaN,NaN,NaN,18,288,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
6,NaN,Rama,Devi,0,NaN,NaN,NaN,2,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
7,NaN,Urmila,Nag,0,NaN,NaN,NaN,18,286,NaN,...,NaN,NaN,CZAPN3954M,NaN,NaN,NaN,NaN,NaN,NaN,
8,NaN,Darshana,Girnale,0,NaN,NaN,NaN,27,468,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
9,NaN,Tanisha,Patel,0,NaN,NaN,NaN,27,487,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
11,NaN,Anita,Devi,0,NaN,NaN,NaN,9,187,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
12,NaN,Rutuja,Gudadhe,0,NaN,NaN,NaN,27,468,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
13,NaN,Saruwar,Jahan,0,NaN,NaN,NaN,18,301,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
14,NaN,Mahaboob,Ansari,0,NaN,NaN,NaN,9,123,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
15,NaN,Khaleda,Molla,0,NaN,NaN,NaN,19,304,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
16,NaN,Nilam,Devi,0,NaN,NaN,NaN,20,324,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
17,NaN,Usha,Devi,0,NaN,NaN,NaN,9,159,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
19,NaN,Usha,Devi,0,NaN,NaN,NaN,9,159,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [31]:
df.columns

Index(['Old_Vendor_ID', 'name', 'name2', 'Balance_LCY', 'address', 'address2',
       'city', 'stateID', 'districtID', 'VendordeliveryCondition',
       'PaymentTerms', 'mobilePhoneNo', 'whatsAppNo', 'eMail', 'fullAddress',
       'BankName', 'bankAccountName', 'bankAccountNo', 'bankAccountIFSC',
       'cspCode', 'Vendor_Type', 'Ledger_Type', 'Vendor_Posting_Group',
       'Post_Code', 'Population', 'pANNo', 'P_A_N_Status',
       'GST_Registration_No', 'GST_Vendor_Type', 'Global_Dimension_1_Filter',
       'Global_Dimension_2_Filter', 'Currency_Filter', 'VendorCode'],
      dtype='object')

In [38]:
# import pandas as pd
# import requests

TENANT_ID = "62a0b673-6bc5-43fb-8ab0-37fb99dbcec9"
COMPANY = "DDCL"

# CLIENT_ID = "YOUR_CLIENT_ID"
# CLIENT_SECRET = "YOUR_CLIENT_SECRET"

EXCEL_FILE = r"E:\Local_Pipelines\Vendors.xlsx"

TOKEN_URL = f"https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/token"

GET_VENDOR_URL = f"https://api.businesscentral.dynamics.com/v2.0/{TENANT_ID}/UAT/ODataV4/Company('{COMPANY}')/VendorListAPI"

# ---------------- TOKEN ----------------

# def get_token():
#     payload = {
#         "client_id": CLIENT_ID,
#         "client_secret": CLIENT_SECRET,
#         "scope": "https://api.businesscentral.dynamics.com/.default",
#         "grant_type": "client_credentials"
#     }

#     r = requests.post(TOKEN_URL, data=payload)
#     r.raise_for_status()
#     return r.json()["access_token"]

# token = get_token()

headers = {
    "Authorization": f"Bearer {token}",
    "Content-Type": "application/json"
}

# df = df[df['stateID'] != 0]

df["VendorCode"] = ""

# ---------------- FETCH ----------------

for index, row in df.iterrows():

    name = str(row["name"]).strip()
    mobile = str(row["mobilePhoneNo"]).strip()

    # Filter by Name + Mobile

    filter_query = f"mobilePhoneNo eq '{mobile}'"
    encoded_filter = quote(filter_query)

    url = f"{GET_VENDOR_URL}?$filter={encoded_filter}"
    print(url)

    r = requests.get(url, headers=headers)

    if r.status_code == 200:
        result = r.json().get("value", [])

        if result:
            vendor_code = result[0]["no"]
            df.at[index, "VendorCode"] = vendor_code
            print(f"✅ Found: {name} → {vendor_code}")
        else:
            print(f"⚠ Not found: {name}")

    else:
        print(f"❌ Error fetching {name}")

# ---------------- SAVE ----------------

df.to_excel("Vendors_With_Codes.xlsx", index=False)

print("\nDone. File created: Vendors_With_Codes.xlsx")

https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%276005547229%27
✅ Found: Jyoti → VEND004649
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%277578966400%27
✅ Found: Nirada → VEND004650
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%279435623392%27
✅ Found: Nikumoni → VEND004651
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%277638872661%27
✅ Found: Momi → VEND004652
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%276901994854%27
✅ Found: Dulal → VEND004653
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%277876820078%27
✅ Found: Rama → VEND004654
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%278099811109%27
✅ Found: Urmila → VEND004655
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%278262890510%27
✅ Found: Darshana → VEND004656
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%278770582787%27
✅ Found: Tanisha → VEND004657
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%279125801858%27
✅ Found: Anita → VEND004658
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%278767751808%27
✅ Found: Rutuja → VEND004659
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%277002831739%27
✅ Found: Saruwar → VEND004660
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%279517032951%27
✅ Found: Mahaboob → VEND004661
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%279093572893%27
✅ Found: Khaleda → VEND000887
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%279955734369%27
✅ Found: Nilam → VEND004663
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%278601967952%27
✅ Found: Usha → VEND004664
https://api.businesscentral.dynamics.com/v2.0/62a0b673-6bc5-43fb-8ab0-37fb99dbcec9/UAT/ODataV4/Company('DDCL')/VendorListAPI?$filter=mobilePhoneNo%20eq%20%279919226240%27
✅ Found: Usha → VEND004665

Done. File created: Vendors_With_Codes.xlsx

In [30]:
df

,Old_Vendor_ID,name,name2,Balance_LCY,address,address2,city,stateID,districtID,VendordeliveryCondition,...,Post_Code,Population,pANNo,P_A_N_Status,GST_Registration_No,GST_Vendor_Type,Global_Dimension_1_Filter,Global_Dimension_2_Filter,Currency_Filter,VendorCode
1,NaN,Jyoti,Devi,0,NaN,NaN,NaN,1,624,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,NaN,Nirada,Deka,0,NaN,NaN,NaN,18,283,NaN,...,NaN,NaN,CKIPD6812R,NaN,NaN,NaN,NaN,NaN,NaN,
3,NaN,Nikumoni,saikia,0,NaN,NaN,NaN,18,288,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,NaN,Momi,Muktiar,0,NaN,NaN,NaN,18,297,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,NaN,Dulal,Borah,0,NaN,NaN,NaN,18,288,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
6,NaN,Rama,Devi,0,NaN,NaN,NaN,2,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
7,NaN,Urmila,Nag,0,NaN,NaN,NaN,18,286,NaN,...,NaN,NaN,CZAPN3954M,NaN,NaN,NaN,NaN,NaN,NaN,
8,NaN,Darshana,Girnale,0,NaN,NaN,NaN,27,468,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
9,NaN,Tanisha,Patel,0,NaN,NaN,NaN,27,487,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
11,NaN,Anita,Devi,0,NaN,NaN,NaN,9,187,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
12,NaN,Rutuja,Gudadhe,0,NaN,NaN,NaN,27,468,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
13,NaN,Saruwar,Jahan,0,NaN,NaN,NaN,18,301,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
14,NaN,Mahaboob,Ansari,0,NaN,NaN,NaN,9,123,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
15,NaN,Khaleda,Molla,0,NaN,NaN,NaN,19,304,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
16,NaN,Nilam,Devi,0,NaN,NaN,NaN,20,324,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
17,NaN,Usha,Devi,0,NaN,NaN,NaN,9,159,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
19,NaN,Usha,Devi,0,NaN,NaN,NaN,9,159,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,