In [1]:
import pyodbc
import os
import pandas as pd
from datetime import datetime, date
import gspread
from google.oauth2.service_account import Credentials
from gspread_dataframe import get_as_dataframe
from dotenv import load_dotenv , find_dotenv # to load .env files
# from google.cloud import storage

# client = storage.Client()
load_dotenv()

True

In [2]:
prod_servr = os.environ.get("DB2_HOST")
prod_user = os.environ.get("DB2_USER")
prod_pass = os.environ.get("DB2_PASS")
prod_db = os.environ.get("DB2_NAME") 

conn = pyodbc.connect(
            f"Driver={{ODBC Driver 17 for SQL Server}};"
            f"Server={prod_servr};"  # Production server
            f"Database={prod_db};"  # Production database
            f"UID={prod_user};"
            f"PWD={prod_pass};"
        )

prod_cursor = conn.cursor()

prod_cursor.fast_executemany = True

In [3]:
# Path to your downloaded key
service_acc_key = os.getenv("gcp_bot_key")

# Define the required scopes
SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

# Authorize
creds = Credentials.from_service_account_file(service_acc_key, scopes=SCOPES)
gc = gspread.authorize(creds)

In [47]:
order_booking = 'https://docs.google.com/spreadsheets/d/1JK8IlIEw6xw7dtqy4Zi0z-7SyQyKdgtOQqFN_aN31Y8/edit?usp=sharing'
order_booking_sheet = gc.open_by_url(order_booking)
order_booking_df = pd.DataFrame(order_booking_sheet.worksheet('Clean Orders').get_all_records())

# Transformation

In [48]:
order_booking_df['Select_Delivery_Date'] = pd.to_datetime(
    order_booking_df['Select_Delivery_Date'].str.strip(),
    format='%d-%m-%Y'
)

order_booking_df['lat_code'] = pd.to_numeric(
    order_booking_df['lat_code'].astype(str).str.strip(),
    errors='coerce'
)

order_booking_df['long_code'] = pd.to_numeric(
    order_booking_df['long_code'].astype(str).str.strip(),
    errors='coerce'
)

order_booking_df['Product_Price'] = pd.to_numeric(
    order_booking_df['Product_Price'].astype(str).str.strip(),
    errors='coerce'
)

order_booking_df['rrp_u'] = (
    'D~' + order_booking_df['route_id']
    .astype(str)
    .str.replace(r'[\n\r]', '', regex=True)
    .str.strip()
)


# order_booking_df['route_id_str'] = order_booking_df['route_id'].apply(lambda x: f"{x:03d}")

order_booking_df['route_id_str'] = order_booking_df['route_id'].astype(str)

order_booking_df[:10]

,Inserted,Type_RRP_Mobile_no,Fetched_RRP,kiosk_code,Select_Delivery_Date,Select_Office,Office_Id,route_id,Select_Product,Product_Id,...,Product_Price,Route name,Amount,lat_code,long_code,Sale Entry Type,Id,userCode,rrp_u,route_id_str
0,Yes,9552489166,Rahul Lillare (ID:99156 ),99156,2026-04-29,Umred - Rajat Mahalkar (ID:77),77,209,Soda Ash,715,...,23.58,MIRI Vaibhavi Route - 77,10611.00,78.122055,20.369634,Dhavak Sale Entry,2,61618,D~209,209
1,Yes,9552489166,Rahul Lillare (ID:99156 ),99156,2026-04-29,Umred - Rajat Mahalkar (ID:77),77,209,Dolomite,198,...,13.61,MIRI Vaibhavi Route - 77,5444.00,78.122055,20.369634,Dhavak Sale Entry,3,61618,D~209,209
2,Yes,9552489166,Rahul Lillare (ID:99156 ),99156,2026-04-29,Umred - Rajat Mahalkar (ID:77),77,209,Salt,541,...,15.24,MIRI Vaibhavi Route - 77,6096.00,78.122055,20.369634,Dhavak Sale Entry,4,61618,D~209,209
3,Yes,9552489166,Rahul Lillare (ID:99156 ),99156,2026-04-29,Umred - Rajat Mahalkar (ID:77),77,209,AOS Liquid,711,...,62.95,MIRI Vaibhavi Route - 77,6295.00,78.122055,20.369634,Dhavak Sale Entry,5,61618,D~209,209
4,Yes,9552489166,Rahul Lillare (ID:99156 ),99156,2026-04-29,Umred - Rajat Mahalkar (ID:77),77,209,Acid Slurry,10,...,135.59,MIRI Vaibhavi Route - 77,33897.50,78.122055,20.369634,Dhavak Sale Entry,6,61618,D~209,209
5,Yes,9552489166,Rahul Lillare (ID:99156 ),99156,2026-04-29,Umred - Rajat Mahalkar (ID:77),77,209,Caustic Lye,99,...,62.95,MIRI Vaibhavi Route - 77,3147.50,78.122055,20.369634,Dhavak Sale Entry,7,61618,D~209,209
6,Yes,9552489166,Rahul Lillare (ID:99156 ),99156,2026-04-29,Umred - Rajat Mahalkar (ID:77),77,209,Sodium Meta Silicate,568,...,40.36,MIRI Vaibhavi Route - 77,2018.00,78.122055,20.369634,Dhavak Sale Entry,8,61618,D~209,209
7,Yes,9552489166,Rahul Lillare (ID:99156 ),99156,2026-04-29,Umred - Rajat Mahalkar (ID:77),77,209,Perfume (Fragrance),480,...,508.47,MIRI Vaibhavi Route - 77,2542.35,78.122055,20.369634,Dhavak Sale Entry,9,61618,D~209,209
8,Yes,9552489166,Rahul Lillare (ID:99156 ),99156,2026-04-29,Umred - Rajat Mahalkar (ID:77),77,209,Colour Balls,151,...,16.95,MIRI Vaibhavi Route - 77,847.50,78.122055,20.369634,Dhavak Sale Entry,10,61618,D~209,209
9,Yes,9678595348,Mampee Borgohain Chetia (ID:106176 ),106176,2026-04-27,Gaurisagar - Chitrali Barkakati (ID:63),63,202,Charcoal Powder,713,...,26.67,MIRI Vaibhavi Route - 63 - 2,2667.00,26.991419,94.637942,Dhavak Sale Entry,11,61618,D~202,202

# Filtering Order

In [62]:
rrp = 94876
officeid = 92
route = '240' 
date1 = '29-09-2026'
date1 = pd.to_datetime(date1, dayfirst=True)
user = 61618

order_booking_df2 = order_booking_df[(order_booking_df['kiosk_code'] == rrp) & (order_booking_df['route_id_str'] == route) & (order_booking_df['Select_Delivery_Date'] == date1) & (order_booking_df['Office_Id'] == officeid)].copy()

# order_booking_df2['Select_Delivery_Date'] = order_booking_df2['Changed_date']

order_booking_df2

,Inserted,Type_RRP_Mobile_no,Fetched_RRP,kiosk_code,Select_Delivery_Date,Select_Office,Office_Id,route_id,Select_Product,Product_Id,...,Product_Price,Route name,Amount,lat_code,long_code,Sale Entry Type,Id,userCode,rrp_u,route_id_str
138,,9569356210,Sangeeta Udyogi Samuh (ID: 94876,94876,2026-09-29,Guwahati Central HUB (ID:92),92,240,Agarbatti Laminated Pouch 80*240 MM,789,...,1.4,MIRI Vaibhavi Route - 90 - 2,21000.0,82.982261,25.304178,Dhavak Sale Entry,141,61618,D~240,240

# Orderbooking

In [63]:
dhavak_grouped_orders = order_booking_df2.groupby([
    "kiosk_code",
    "route_id_str",
    "Select_Delivery_Date",
    "Office_Id",
    "lat_code",
    "long_code",
    "userCode",
])

print('kiosk_code ',
    'route_id_str ',
    'Select_Delivery_Date ',
    'Office_Id ',
    'lat_code ',
    'long_code ',
    'userCode ')

for i in dhavak_grouped_orders.groups:
    print(i)

kiosk_code  route_id_str  Select_Delivery_Date  Office_Id  lat_code  long_code  userCode
(94876, '240', Timestamp('2026-09-29 00:00:00'), 92, 82.9822609, 25.3041776, 61618)

In [64]:
for key, order_df in dhavak_grouped_orders:

    kiosk_code, route_id_str, delivery_date, office_id, lat, long, userCode = key
    
    for _, row in order_df.iterrows():

            product_id = row['Product_Id']
            qty = pd.to_numeric(row['Type_Quantity'], errors='coerce')

            prod_cursor.execute("""
            EXEC DROP_DrishteeDhavak..usp_check_dhavak_stock ?,?,?,?
            """,
            int(product_id),
            int(office_id),
            None,
            pd.to_datetime(delivery_date).to_pydatetime()
            )

            stock = prod_cursor.fetchone()

            product_id = stock[0]
            product_name = stock[5]
            available_quantity = stock[1]
            stock_available = stock[4]

            print(f'Product Name: {product_name} | Available Quantity: {available_quantity} | Product Id: {product_id} | Stock Available: {stock_available}')

print(order_booking_df2[['Product_Id','Type_Quantity']])

Product Name: MIRI Agarbatti Laminated Pouch 80*240 MM 1Pcs. | Available Quantity: 186600 | Product Id: 789 | Stock Available: 175200
     Product_Id  Type_Quantity
138         789          15000

In [65]:
for key, order_df in dhavak_grouped_orders:
    kiosk_code, route_id_str, delivery_date, office_id, lat, long, userCode = key
    # print(order_df)
    for _, row in order_df.iterrows():
        product_id = row['Product_Id']
        qty = pd.to_numeric(row['Type_Quantity'], errors='coerce')
        package_type = ''
        total_amt = row['Amount']
        print(f'Product Id: {product_id} | Quantity: {qty} | Package Type: {package_type} | Total Amount: {total_amt}')

Product Id: 789 | Quantity: 15000 | Package Type:  | Total Amount: 21000.0

# Orderbooking Insert

In [66]:
for key, order_df in dhavak_grouped_orders:

    kiosk_code, route_id_str, delivery_date, office_id, lat, long, userCode = key

    print(f"Creating Order for Kiosk kiosk_code, route_id, delivery_date, office_id, lat, long, userCode \n{kiosk_code, route_id_str, delivery_date, office_id, lat, long, userCode}\n")

    # STEP 1 : CREATE ORDER HEADER
    prod_cursor.execute("""
    EXEC DROP_DrishteeDhavak..sp_scm__rrp_order_booking_insert
        ?,?,?,?,?,?,?
    """,
    int(kiosk_code),
    str(route_id_str),
    pd.to_datetime(delivery_date).to_pydatetime(),
    int(userCode),
    float(long),
    float(lat),
    int(office_id)
    )

    result = prod_cursor.fetchone()

    messagecode = result[0]
    message = result[1]
    order_id = result[2]
    
    print("Order Created:", order_id)
    print("Message Code:", messagecode, "Message:", message, "Order ID:", order_id ,"\n")

    # STEP 2 : PROCESS PRODUCTS
    for _, row in order_df.iterrows():

        product_id = row['Product_Id']
        qty = pd.to_numeric(row['Type_Quantity'], errors='coerce')
        package_type = ''
        total_amt = row['Amount']

        prod_cursor.execute("""
        EXEC DROP_DrishteeDhavak..usp_check_dhavak_stock ?,?,?,?
        """,
        int(product_id),
        int(office_id),
        None,
        pd.to_datetime(delivery_date).to_pydatetime()
        )

        stock = prod_cursor.fetchone()

        if stock is None:
            print(f"\nSkipping Product {product_id} (No stock record found)\n")
            prod_cursor.commit()
            conn.commit()
            continue
        
        product_id = stock[0]
        product_name = stock[5]
        available_quantity = stock[1]
        stock_available = stock[4]

        if float(stock_available) >= qty:

            print(f"Inserting Product {product_name} ID {product_id} for orderId {order_id}")

            prod_cursor.execute("""
            EXEC DROP_DrishteeDhavak..sp_scm__rrp_order_booking_detail_insert
                ?,?,?,?,?,?
            """,
            int(order_id),
            int(userCode),
            int(product_id),
            int(qty),
            package_type,
            float(total_amt)
            )

            print("Completing Status_check for Order ID:", order_id)

# Added on 01-09-2026
            prod_cursor.execute("""
            UPDATE DROP_DrishteeDhavak..OrderBooking_rrp SET Status_check = 'Completed' WHERE order_id = ?""",
                        int(order_id)
            )

            prod_cursor.commit()
            conn.commit()
            
        else:
            print(f"\nSkipping Product {product_name} ID {product_id}, for route_id:{route_id_str}, kiosk_code:{kiosk_code}, lat:{lat}, long:{long}, delivery_date:{delivery_date}, office_id:{office_id}, userCode:{userCode},  OrderID:{order_id}\n")
    
    prod_cursor.commit()
    conn.commit()

print("\nOrderbooking Data inserted successfully...!")

Creating Order for Kiosk kiosk_code, route_id, delivery_date, office_id, lat, long, userCode
(94876, '240', Timestamp('2026-09-29 00:00:00'), 92, 82.9822609, 25.3041776, 61618)

Order Created: 6935
Message Code: 1 Message: Data submitted succesfully. Order ID: 6935

Inserting Product MIRI Agarbatti Laminated Pouch 80*240 MM 1Pcs. ID 789 for orderId 6935
Completing Status_check for Order ID: 6935

Orderbooking Data inserted successfully...!

# Import to Dhavak

In [67]:
prod_cursor.execute(f"""
EXEC DROP_mis..select_orderfromdhavak_with_stock_proc ?,?,?
""",
'240','2026-09-29',92  
# int(route_id), pd.to_datetime(delivery_date).to_pydatetime(), int(office_id)
)

columns = [col[0] for col in prod_cursor.description]
stock_rows = [tuple(i) for i in prod_cursor.fetchall()]

stock_df = pd.DataFrame.from_records(stock_rows, columns=columns)
stock_df

,product_id,quantity,route_id,office_id,delivery_date,tax,unit_price,product_name,peti_quantity,tax_amount,available_quanitty,last_purchase,brand_name,created_by,package_type,total_amt,rrp_ID,RRP_mobile_Name
0,789,15000,240,92,2026-09-29,18.00,1.65,MIRI Agarbatti Laminated Pouch 80*240 MM 1 Pcs.,5000,3780.00,160200,0.72,117,61618,,21000.00,94876,9569356210 - Sangeeta Udyogi Samuh

In [68]:
order_booking_df2['Product_Id'] = order_booking_df2['Product_Id'].astype(int)
order_booking_df2['route_id_str'] = order_booking_df2['route_id_str'].astype(int)
order_booking_df2['Office_Id'] = order_booking_df2['Office_Id'].astype(int)
stock_df['product_id'] = stock_df['product_id'].astype(int)
stock_df['route_id'] = stock_df['route_id'].astype(int)
stock_df['office_id'] = stock_df['office_id'].astype(int)
order_booking_df2['Select_Delivery_Date'] = pd.to_datetime(order_booking_df2['Select_Delivery_Date'])
stock_df['delivery_date'] = pd.to_datetime(stock_df['delivery_date'])

merged_df = pd.merge(
    order_booking_df2,
    stock_df,
    left_on=['Product_Id', 'route_id_str', 'Select_Delivery_Date', 'Office_Id'],
    right_on=['product_id', 'route_id', 'delivery_date', 'office_id'],
    how='inner'
    )

merged_df

,Inserted,Type_RRP_Mobile_no,Fetched_RRP,kiosk_code,Select_Delivery_Date,Select_Office,Office_Id,route_id_x,Select_Product,Product_Id,...,peti_quantity,tax_amount,available_quanitty,last_purchase,brand_name,created_by,package_type,total_amt,rrp_ID,RRP_mobile_Name
0,,9569356210,Sangeeta Udyogi Samuh (ID: 94876,94876,2026-09-29,Guwahati Central HUB (ID:92),92,240,Agarbatti Laminated Pouch 80*240 MM,789,...,5000,3780.00,160200,0.72,117,61618,,21000.00,94876,9569356210 - Sangeeta Udyogi Samuh

In [69]:
merged_df1 = merged_df[['product_id', 'quantity', 'route_id_y', 'office_id', 'delivery_date',
        'tax', 'unit_price', 'product_name', 'peti_quantity', 'tax_amount',
        'available_quanitty', 'last_purchase', 'brand_name','total_amt']].drop_duplicates().copy()

mis_grouped_orders = order_booking_df2.groupby([
    'rrp_u',
    'route_id_str',
    'Select_Delivery_Date',
    'userCode',
    'Office_Id'
])

print('rrp_u ',
    'route_id_str ',
    'Select_Delivery_Date ',
    'userCode ',
    'Office_Id ')

for i in mis_grouped_orders.groups:
    print(i)

rrp_u  route_id_str  Select_Delivery_Date  userCode  Office_Id
('D~240', 240, Timestamp('2026-09-29 00:00:00'), 61618, 92)

# Import to Dhavak Insertion

In [70]:
for keys, order_df in mis_grouped_orders:
    rrp_u, route_id_str, delivery_date, userCode, office_id = keys

    print(f"\nProcessing Order → RRP:{rrp_u} route:{route_id_str} delivery_date:{delivery_date} userCode:{userCode} office_id:{office_id}")

    delivery_date = pd.to_datetime(delivery_date).to_pydatetime()

    prod_cursor.execute("""
    EXEC Drop_mis..OrderBooking_Insert_proc ?,?,?,?,?
    """,
    str(rrp_u),
    str(route_id_str),
    delivery_date,
    int(userCode),
    int(office_id)
    )

    result = prod_cursor.fetchone()
    order_id = result[0]
    print("Order ID:", order_id)

    if result is None:
        print("Order creation failed\n")
        continue

    print(f"Fetching stock for route_id:{route_id_str}, delivery_date:{delivery_date}, office_id:{office_id}\n")

    prod_cursor.fast_executemany = True

    prod_cursor.execute("""
    EXEC Drop_mis..select_orderfromdhavak_with_stock_proc ?,?,?
    """,
    str(route_id_str),
    delivery_date,
    int(office_id)
    )
    columns = [col[0] for col in prod_cursor.description]
    stock_rows = [tuple(i) for i in prod_cursor.fetchall()]
    stock_df = pd.DataFrame.from_records(stock_rows, columns=columns)

    stock_df1 = stock_df[~stock_df['unit_price'].isna()].copy()

    if not stock_df1.shape[0]:
        print("No stock returned\n")
        continue
    
    order_booking_df2['Product_Id'] = order_booking_df2['Product_Id'].astype(int)
    order_booking_df2['route_id_str'] = order_booking_df2['route_id_str'].astype(int)
    order_booking_df2['Office_Id'] = order_booking_df2['Office_Id'].astype(int)
    stock_df1['product_id'] = stock_df1['product_id'].astype(int)
    stock_df1['route_id'] = stock_df1['route_id'].astype(int)
    stock_df1['office_id'] = stock_df1['office_id'].astype(int)
    order_booking_df2['Select_Delivery_Date'] = pd.to_datetime(order_booking_df2['Select_Delivery_Date'])
    stock_df1['delivery_date'] = pd.to_datetime(stock_df1['delivery_date'])

    merged_df = pd.merge(
    order_booking_df2,
    stock_df1,
    left_on=['Product_Id', 'route_id_str', 'Select_Delivery_Date', 'Office_Id'],
    right_on=['product_id', 'route_id', 'delivery_date', 'office_id'],
    how='inner'
    )

    merged_df1 = merged_df[['product_id', 'quantity', 'route_id_y', 'office_id', 'delivery_date',
        'tax', 'unit_price', 'product_name', 'peti_quantity', 'tax_amount',
        'available_quanitty', 'last_purchase', 'brand_name','total_amt']].drop_duplicates().copy()

    for row in merged_df1.itertuples():

        print(f"Inserting Product {row.product_id} for orderId {order_id}")

        prod_cursor.execute("""
        EXEC Drop_mis..OrderBookingDetail_Insert_proc
            ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?
        """,
        int(order_id),
        int(row.product_id),
        float(row.quantity or 0),
        float(row.unit_price or 0),
        int(userCode),
        float(row.tax or 0),
        float(row.tax_amount or 0),
        int(office_id),
        float(row.peti_quantity or 0),
        float(row.unit_price or 0),
        float(row.unit_price or 0),
        float(0),
        'F',
        'N',
        float(row.total_amt),
        '',
        int(userCode)
        )

    prod_cursor.commit()
    conn.commit()

    print(f"\nOrder Completed for: RRP={rrp_u}, route_id={route_id_str}, delivery_date={delivery_date}, office_id={office_id}, userCode={userCode}, order_id={order_id}")

print(f"\nOrderbooking Data Inserted...!")

Processing Order → RRP:D~240 route:240 delivery_date:2026-09-29 00:00:00 userCode:61618 office_id:92
Order ID: 2027029092023
Fetching stock for route_id:240, delivery_date:2026-09-29 00:00:00, office_id:92

Inserting Product 789 for orderId 2027029092023

Order Completed for: RRP=D~240, route_id=240, delivery_date=2026-09-29 00:00:00, office_id=92, userCode=61618, order_id=2027029092023

Orderbooking Data Inserted...!

# Issue to Executive

In [73]:
RRA_grouped_orders = order_booking_df2.groupby(['userCode', 'Select_Delivery_Date','route_id_str', 'Office_Id'])

print('userCode ', 'Select_Delivery_Date ','route_id_str ', 'Office_Id')
for i in RRA_grouped_orders.groups:
    print(i)

userCode  Select_Delivery_Date  route_id_str  Office_Id
(61618, Timestamp('2026-09-29 00:00:00'), 240, 92)

# Issue to Executive Insert

In [74]:
for keys, order_df in RRA_grouped_orders:
    userCode, Delivery_Date,route_id_str, Office_Id = keys

    print(f"\nIssuing Order :\nuserCode:{userCode} Delivery_Date:{Delivery_Date} route_id:{route_id_str} Office_Id:{Office_Id}")

    delivery_date = pd.to_datetime(Delivery_Date).to_pydatetime()

    prod_cursor.execute("""
    SELECT CONCAT(LTRIM(TRIM(UserFirstName)),' ',LTRIM(TRIM(UserMiddleName)),' ',LTRIM(TRIM(UserLastName))) transporter_name
    FROM DROP_DrishteeDhavak..usermaster WHERE UserDrishteeID = ?
    """,
    int(userCode)
    )
    columns = [col[0] for col in prod_cursor.description]
    rows = [tuple(i) for i in prod_cursor.fetchall()]
    dhavak = pd.DataFrame.from_records(rows, columns=columns)

    print(f"Issue For Dhavak: {dhavak.transporter_name[0]}\n")

    prod_cursor.execute("""
         DROP_mis..ProductIssueRRA_insert_update_RM_PM_Sale ?,?,?,?,?,?,?,?,?,?
        """,
        int(userCode),                                      
        delivery_date,                                      
        'EMP967',                                      
        str(route_id_str),                                    
        'I',                                      
        int(Office_Id),                  
        str(dhavak.transporter_name[0]),                   
        'MH 32 OH 8003',                    
        10,                    
        100
        )

    
    # prod_cursor.execute("""
    #  DROP_mis..ProductIssueRRA_insert_update ?,?,?,?,?,?,?,?,?,?
    # """,
    # int(userCode),                                      
    # delivery_date,                                      
    # 'EMP967',                                      
    # str(route_id_str),                                    
    # 'I',                                      
    # int(Office_Id),                  
    # str(dhavak.transporter_name[0]),                   
    # 'MH 32 OH 8003',                    
    # 10,                    
    # 100
    # )
    

prod_cursor.commit()
conn.commit()

print("RRA Issued Completed..!")

Issuing Order :
userCode:61618 Delivery_Date:2026-09-29 00:00:00 route_id:240 Office_Id:92
Issue For Dhavak: Amit  Kumar

RRA Issued Completed..!

# Sale Entry

In [75]:
sale_grouped_orders = order_booking_df2.groupby(['kiosk_code','route_id_str', 'Select_Delivery_Date','userCode','Office_Id'])

for i in sale_grouped_orders.groups:
    print(i)

(94876, 240, Timestamp('2026-09-29 00:00:00'), 61618, 92)

In [76]:
for key , order_df in sale_grouped_orders:

    kiosk_code, route_id_str, delivery_date, userCode, Office_Id = key

    delivery_date = pd.to_datetime(delivery_date).to_pydatetime()

    print(f"\nInserting Order for Kiosk {kiosk_code}, Route {route_id_str}, Delivery Date {delivery_date}, User {userCode}")

    # prod_cursor.execute("""
    # EXEC DROP_DrishteeDhavak..sp_scm_rrp_sale_booking_insert ?,?,?,?,? <-- Old Code
    #                     """,
    #                     int(kiosk_code),
    #                     str(route_id_str),
    #                     delivery_date,
    #                     int(userCode),
    #                     int(Office_Id)
    #                 )
    
    prod_cursor.execute("""
        EXEC DROP_mis..sp_scm_rrp_sale_booking_insert ?,?,?,?,?
                            """,
                            int(kiosk_code),
                            str(route_id_str),
                            delivery_date,
                            int(userCode),
                            int(Office_Id)
                        )

    print("Inserted...!")
    
prod_cursor.commit()
conn.commit()

print("Sale Entry Completed..!")

Inserting Order for Kiosk 94876, Route 240, Delivery Date 2026-09-29 00:00:00, User 61618
Inserted...!
Sale Entry Completed..!