# ***Pipeline To Fetch Data From Google Doc***

You’ll need to create a service account in Google Cloud Console → enable Google Sheets API → download the JSON key → and share your Sheet with the service account’s email (e.g. service-account@yourproject.iam.gserviceaccount.com) with Editor permission.

In [1]:
import pyodbc
import os
import io
import pandas as pd
from datetime import datetime, date

import gspread
from gspread_dataframe import get_as_dataframe

from google.oauth2 import service_account
from google.oauth2.service_account import Credentials

from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload

from dotenv import load_dotenv , find_dotenv # to load .env files
# from google.cloud import storage

# client = storage.Client()
load_dotenv() # Load .env file

c:\Users\handa\AppData\Local\Programs\Python\Python310\lib\site-packages\google\api_core\_python_version_support.py:255: FutureWarning: You are using a Python version (3.10.6) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)

True

# Connecting to Warehouse DB

In [2]:
warehouse_servr = os.environ.get("DB1_HOST")
warehouse_user = os.environ.get("DB1_USER")
warehouse_pass = os.environ.get("DB1_PASS")
warehouse_db = os.environ.get("DB1_NAME") 

conn = pyodbc.connect(
            f"Driver={{ODBC Driver 17 for SQL Server}};"
            f"Server={warehouse_servr};"  # Warehouse server
            f"Database={warehouse_db};"  # Warehouse database
            f"UID={warehouse_user};"
            f"PWD={warehouse_pass};"
        )

warehouse_cursor = conn.cursor()

warehouse_cursor.fast_executemany = True

In [3]:
prod_servr = os.environ.get("DB2_HOST")
prod_user = os.environ.get("DB2_USER")
prod_pass = os.environ.get("DB2_PASS")
prod_db = os.environ.get("DB2_NAME") 

conn = pyodbc.connect(
            f"Driver={{ODBC Driver 17 for SQL Server}};"
            f"Server={prod_servr};"  # Warehouse server
            f"Database={prod_db};"  # Warehouse database
            f"UID={prod_user};"
            f"PWD={prod_pass};"
        )

prod_cursor = conn.cursor()

prod_cursor.fast_executemany = True

# Offline Excel

In [3]:
# csp_vldf = pd.read_excel(r'E:\Local_Pipelines\CSP_AND_VATIKA.xlsx')
# csp_vldf

In [13]:
csp_vldf.columns

Index(['Bank', 'Unnamed: 1', 'Active\nAgent_ID', 'Agent Name', 'State',
       'District Name', 'Territory', 'Employee', 'Agent\nStatus',
       'Nearest Vatika ', 'Vatika- Block', 'Distance- from CSP', 'Remarks'],
      dtype='object')

In [22]:
grp_df = csp_vldf.groupby(['State',
       'District Name','Nearest Vatika '])

for i in grp_df.groups:
    print(i)

('ASSAM', 'BARPETA', 'Niz Chenga')
('ASSAM', 'BISWANATH', 'Kalyanpur')
('ASSAM', 'BONGAIGAON', 'Borigaon')
('ASSAM', 'BONGAIGAON', 'Dewhati')
('ASSAM', 'CHARAIDEO', 'BORPATHAR')
('ASSAM', 'CHARAIDEO', 'HAPEKHATI')
('ASSAM', 'CHARAIDEO', 'HOLLOWPHUKON')
('ASSAM', 'CHARAIDEO', 'SAPEKHATI')
('ASSAM', 'CHARAIDEO', 'SUKAFA')
('ASSAM', 'CHARAIDEO', 'TENGALIBAM')
('ASSAM', 'CHIRANG', 'North Salmara')
('ASSAM', 'DARRANG', 'Demornoi')
('ASSAM', 'DARRANG', 'Hazarika para')
('ASSAM', 'DARRANG', 'Niz baruajhar')
('ASSAM', 'DARRANG', 'Ourala')
('ASSAM', 'DARRANG', 'lotakat')
('ASSAM', 'DARRANG', 'niz barauajhar')
('ASSAM', 'DARRANG', 'niz baruahjar')
('ASSAM', 'DARRANG', 'no 2 kuwarpukhuri')
('ASSAM', 'DARRANG', 'no 3 gala dikash')
('ASSAM', 'DARRANG', 'no 3 galandi kash')
('ASSAM', 'DARRANG', 'no 3 galndikash')
('ASSAM', 'DHUBRI', 'Bagmari')
('ASSAM', 'DHUBRI', 'Bangalipara')
('ASSAM', 'DHUBRI', 'Barkanda')
('ASSAM', 'DHUBRI', 'Chapar')
('ASSAM', 'DHUBRI', 'Falimari')
('ASSAM', 'DHUBRI', 'Kacharihat')
('ASSAM', 'DHUBRI', 'Kachukata')
('ASSAM', 'DHUBRI', 'Kadamtola')
('ASSAM', 'DHUBRI', 'Lakhiganj')
('ASSAM', 'DHUBRI', 'Raniganj')
('ASSAM', 'DIBRUGARH', 'BOKUL')
('ASSAM', 'DIBRUGARH', 'DIKOM')
('ASSAM', 'DIBRUGARH', 'Gazpuria')
('ASSAM', 'DIBRUGARH', 'Hiloidhari')
('ASSAM', 'DIBRUGARH', 'KHOWANG KHOLOLUA')
('ASSAM', 'DIBRUGARH', 'MANCOTTA')
('ASSAM', 'DIBRUGARH', 'MODERKHAT')
('ASSAM', 'DIBRUGARH', 'Parijat')
('ASSAM', 'DIBRUGARH', 'Telpani')
('ASSAM', 'Darrang', 'Sarabari')
('ASSAM', 'GOALPARA', 'Dariduri')
('ASSAM', 'GOALPARA', 'Khalichavita')
('ASSAM', 'GOALPARA', 'Kumri')
('ASSAM', 'GOALPARA', 'Tukura')
('ASSAM', 'GOLAGHAT', 'ADARSHA GOMARI GURI')
('ASSAM', 'GOLAGHAT', 'BILOTIA')
('ASSAM', 'GOLAGHAT', 'DHEKIAL')
('ASSAM', 'GOLAGHAT', 'GALABILL')
('ASSAM', 'GOLAGHAT', 'GAMARIGURI')
('ASSAM', 'GOLAGHAT', 'GELABIL')
('ASSAM', 'GOLAGHAT', 'GILADHARI')
('ASSAM', 'GOLAGHAT', 'KAROIGHAT')
('ASSAM', 'GOLAGHAT', 'KORAIGHAT')
('ASSAM', 'GOLAGHAT', 'LETEKUJAN')
('ASSAM', 'GOLAGHAT', 'MOHARAMUKH')
('ASSAM', 'GOLAGHAT', 'NOUJAN')
('ASSAM', 'GOLAGHAT', 'PANJAN')
('ASSAM', 'GOLAGHAT', 'PHOLONGIA')
('ASSAM', 'GOLAGHAT', 'POCHIM BORPOTHAR')
('ASSAM', 'GOLAGHAT', 'PREMHORA')
('ASSAM', 'GOLAGHAT', 'PUP BORPOTHAR')
('ASSAM', 'GOLAGHAT', 'SARUPOTHAR')
('ASSAM', 'GOLAGHAT', 'SENSUWA')
('ASSAM', 'GOLAGHAT', 'SIMANTA')
('ASSAM', 'GOLAGHAT', 'TENGA NI')
('ASSAM', 'GOLAGHAT', 'UTTOR GURU JUGONIA')
('ASSAM', 'HOJAI', '1 no kaki')
('ASSAM', 'HOJAI', 'Mourajhar(Inactive)')
('ASSAM', 'HOJAI', 'Rajbari(ina)')
('ASSAM', 'HOJAI', 'Thaisupar(Inactive)')
('ASSAM', 'HOJAI', 'ambari')
('ASSAM', 'HOJAI', 'dimrupar(Inactive)')
('ASSAM', 'HOJAI', 'kumurakata(ina)')
('ASSAM', 'JORHAT', '71 NO KHONGIA')
('ASSAM', 'JORHAT', 'BALIGAON')
('ASSAM', 'JORHAT', 'BIRINASAHEK')
('ASSAM', 'JORHAT', 'BOKAHULA')
('ASSAM', 'JORHAT', 'CHUNGI')
('ASSAM', 'JORHAT', 'DAHIKUR ')
('ASSAM', 'JORHAT', 'GORUMORA')
('ASSAM', 'JORHAT', 'KACHUKHAT')
('ASSAM', 'JORHAT', 'KAKOJAN')
('ASSAM', 'JORHAT', 'LADOIGARH')
('ASSAM', 'JORHAT', 'MADHAPUR')
('ASSAM', 'JORHAT', 'RANGAJAN ')
('ASSAM', 'JORHAT', 'SALIKHUWA')
('ASSAM', 'KAMRUP', 'dohali dokohola')
('ASSAM', 'KAMRUP', 'pachim chaygaon')
('ASSAM', 'KAMRUP', 'rampur')
('ASSAM', 'KAMRUP', 'satpur')
('ASSAM', 'KAMRUP', 'sualkuchi(ina)')
('ASSAM', 'KOKRAJHAR', 'Tushpara')
('ASSAM', 'LAKHIMPUR', 'Azad')
('ASSAM', 'LAKHIMPUR', 'Chaboti')
('ASSAM', 'LAKHIMPUR', 'Doolahat sonapur')
('ASSAM', 'LAKHIMPUR', 'Harhai')
('ASSAM', 'LAKHIMPUR', 'Pathalipahar')
('ASSAM', 'MORIGAON', 'bhurbhandha')
('ASSAM', 'MORIGAON', 'boghora(INA)')
('ASSAM', 'MORIGAON', 'ghagua(ina)')
('ASSAM', 'MORIGAON', 'gormari(ina)')
('ASSAM', 'MORIGAON', 'guva(ina)')
('ASSAM', 'MORIGAON', 'jagibhakatgaon')
('ASSAM', 'MORIGAON', 'manipur(ina)')
('ASSAM', 'MORIGAON', 'salmari(ina)')
('ASSAM', 'NAGAON', 'Aibheti(Inactive)')
('ASSAM', 'NAGAON', 'Batamari(Inactive)')
('ASSAM', 'NAGAON', 'Borbari(Inactive)')
('ASSAM', 'NAGAON', 'Deudhar')
('ASSAM', 'NAGAON', 'Phulaguri(Inactive)')
('ASSAM', 'NAGAON', 'Rangaloo(Inactive)')
('ASSAM', 'NAGAON', 'dakhin nonoi')
('ASSAM', 'NAGAON', 'dewdhar')
('ASSAM', 'NAGAON', 'jamuguri kujidah(ina)')
('ASSAM', 'NAGAON', 'nizhatichung')
('ASSAM', 'NAGAON', 'phulaguri(ina)')
('ASSAM', 'NAGAON', 'puranigudam(Inactive)Brahampur')
('ASSAM', 'SIVASAGAR', 'ATHABARI')
('ASSAM', 'SIVASAGAR', 'BORUAHPUKHURI')
('ASSAM', 'SIVASAGAR', 'Charing')
('ASSAM', 'SIVASAGAR', 'DEMOW')
('ASSAM', 'SIVASAGAR', 'DISANGMUKH')
('ASSAM', 'SIVASAGAR', 'Deuraja ')
('ASSAM', 'SIVASAGAR', 'HAHCHARA')
('ASSAM', 'SIVASAGAR', 'JOYMOTI')
('ASSAM', 'SIVASAGAR', 'KHANAMUKH')
('ASSAM', 'SIVASAGAR', 'LAKUWA')
('ASSAM', 'SIVASAGAR', 'NITAIPUKHURI')
('ASSAM', 'SIVASAGAR', 'Nagalamora')
('ASSAM', 'SIVASAGAR', 'PANBECHA')
('ASSAM', 'SIVASAGAR', 'PEOLIPHUKON')
('ASSAM', 'SIVASAGAR', 'RAMONI')
('ASSAM', 'SIVASAGAR', 'Romoni ')
('ASSAM', 'SIVASAGAR', 'Rudrasagar')
('ASSAM', 'SIVASAGAR', 'SILAKUTI')
('ASSAM', 'SIVASAGAR', 'kaiwaimari')
('ASSAM', 'SIVASAGAR', 'kalibosti')
('ASSAM', 'SIVASAGAR', 'khelua')
('ASSAM', 'SIVASAGAR', 'konwarpur')
('ASSAM', 'SONITPUR', 'Bamunghula')
('ASSAM', 'SONITPUR', 'Batashipur')
('ASSAM', 'SONITPUR', 'Belsiri')
('ASSAM', 'SONITPUR', 'Besseria')
('ASSAM', 'SONITPUR', 'Bhotpara')
('ASSAM', 'SONITPUR', 'Borchala')
('ASSAM', 'SONITPUR', 'Chapai')
('ASSAM', 'SONITPUR', 'Chitalmari')
('ASSAM', 'SONITPUR', 'Dolabari')
('ASSAM', 'SONITPUR', 'Gormara')
('ASSAM', 'SONITPUR', 'Hugrajuli')
('ASSAM', 'SONITPUR', 'Khalihamari')
('ASSAM', 'SONITPUR', 'Lokra`')
('ASSAM', 'SONITPUR', 'Naharani')
('ASSAM', 'SONITPUR', 'Panchmile')
('ASSAM', 'SONITPUR', 'Rangachakua')
('ASSAM', 'SONITPUR', 'Rowmari')
('ASSAM', 'SONITPUR', 'Thakurbari')
('ASSAM', 'SONITPUR', 'Uttar Nagsankar')
('ASSAM', 'SONITPUR', 'Vitor porua')
('ASSAM', 'SONITPUR', 'kehurakanda')
('ASSAM', 'SONITPUR', 'singari')
('ASSAM', 'TINSUKIA', 'AMBIKAPUR')
('ASSAM', 'TINSUKIA', 'HOLOGAON')
('ASSAM', 'TINSUKIA', 'KACHOMARI ')
('ASSAM', 'TINSUKIA', 'KAKOPOTHAR')
('ASSAM', 'TINSUKIA', 'KAKOPOTHAR ROBORGURI')
('ASSAM', 'TINSUKIA', 'PANITOLA')
('ASSAM', 'TINSUKIA', 'RAJGARH')
('ASSAM', 'UDALGURI', 'balipara')
('ASSAM', 'UDALGURI', 'dimaruguri')
('ASSAM', 'UDALGURI', 'gerua')
('ASSAM', 'UDALGURI', 'jhargaon')
('ASSAM', 'UDALGURI', 'khoirabari')
('ASSAM', 'UDALGURI', 'naptipara')
('ASSAM', 'biswanath', 'Niz sootea')
('BIHAR', 'BANKA', 'Srinagar')
('BIHAR', 'BHAGALPUR', 'Akidatpur')
('MADHYA PRADESH', 'UJJAIN', 'Bhatuni')
('MADHYA PRADESH', 'UJJAIN', 'Khajjukhedi')
('MADHYA PRADESH', 'UJJAIN', 'Nanded')
('MAHARASHTRA', 'AKOLA', 'Ridhora')
('MAHARASHTRA', 'AMRAVATI', 'Devgaon')
('MAHARASHTRA', 'AMRAVATI', 'Dhamangaon')
('MAHARASHTRA', 'AMRAVATI', 'Dhankheda')
('MAHARASHTRA', 'AMRAVATI', 'Gaurkheda (kumbi)')
('MAHARASHTRA', 'AMRAVATI', 'Kakda')
('MAHARASHTRA', 'AMRAVATI', 'Kavitha')
('MAHARASHTRA', 'BULDHANA', 'Sarolapir')
('MAHARASHTRA', 'BULDHANA', 'Takarkhed Helga')
('MAHARASHTRA', 'JALGAON', 'Anapur')
('MAHARASHTRA', 'JALGAON', 'Anipur')
('MAHARASHTRA', 'JALGAON', 'Uthkheda ,Abhoda')
('MAHARASHTRA', 'NAGPUR', 'Methpanjra')
('MAHARASHTRA', 'NAGPUR', 'Udasa')
('MAHARASHTRA', 'WARDHA', 'Anji')
('MAHARASHTRA', 'WARDHA', 'Mahabala')
('MAHARASHTRA', 'WARDHA', 'Rasulabad')
('MAHARASHTRA', 'WARDHA', 'Surgaon')
('MAHARASHTRA', 'YAVATMAL', 'Bori Arab')
('MAHARASHTRA', 'YAVATMAL', 'Khadka')
('MAHARASHTRA', 'YAVATMAL', 'Khateshvar')
('ODISHA', 'BALESHWAR', '1.Gopinathpur\n2.Bhograi')
('ODISHA', 'BALESHWAR', 'Nabera')
('ODISHA', 'BHADRAK', 'Rahania')
('ODISHA', 'DHENKANAL', '1.Mathatentulia\n2.Raitala\n3.Gundurapasi\n4.Sorisiapada')
('ODISHA', 'DHENKANAL', 'Kerajoli')
('ODISHA', 'MAYURBHANJ', 'Dugudha')
('ODISHA', 'MAYURBHANJ', 'Patalipura')
('ODISHA', 'MAYURBHANJ', 'Sanraikalli')
('UTTAR PRADESH', 'KHERI', ' Dhuskia')
('WEST BENGAL', 'COOCH BEHAR', 'AMBARI')
('WEST BENGAL', 'COOCH BEHAR', 'CHAKCHAKA')
('WEST BENGAL', 'COOCH BEHAR', 'KHAPAIDANGA')
('WEST BENGAL', 'COOCH BEHAR', 'MARICHBARI')
('WEST BENGAL', 'DAKSHIN DINAJPUR', 'AUTINA')
('WEST BENGAL', 'DARJEELING', 'KAINJALIA')
('WEST BENGAL', 'DARJEELING', 'KHARIBARI')
('WEST BENGAL', 'NADIA', 'Baganchara')
('WEST BENGAL', 'NORTH 24 PARGANAS', 'Banglani')
('WEST BENGAL', 'NORTH 24 PARGANAS', 'Bithari Hakimpur')
('WEST BENGAL', 'NORTH 24 PARGANAS', 'Chandpur')
('WEST BENGAL', 'NORTH 24 PARGANAS', 'Polerhat')
('WEST BENGAL', 'SOUTH 24 PARGANAS', 'Benota 1')
('WEST BENGAL', 'SOUTH 24 PARGANAS', 'Benota 2')
('WEST BENGAL', 'SOUTH 24 PARGANAS', 'Bhagabanpur')
('WEST BENGAL', 'SOUTH 24 PARGANAS', 'Daria')
('WEST BENGAL', 'SOUTH 24 PARGANAS', 'Polerhat')
('WEST BENGAL', 'SOUTH 24 PARGANAS', 'Shanpukur')
('WEST BENGAL', 'UTTAR DINAJPUR', 'AMRITA KHANDA , AMRITAKHANDA 2')

In [28]:
results = []

for (state,district,csp_vatika), val in grp_df:

    print(state,district,csp_vatika)
    prod_cursor.execute(
        '''
            SELECT DISTINCT
            v.VatikaId , v.VatikaName , v.IsDelete, bl.Block_Code , bl.Block_Name
            ,ds.District_id , ds.District_name , st.State_Code , st.State_Name , v.bhk_village_code
            FROM drishtee_vatika..Vatika v
            LEFT JOIN DDCL_ERP..TblVillage_Master vl ON vl.Village_Code = v.VillageId
            LEFT JOIN DDCL_ERP..TblPanchayt_Master pn oN vl.Panchayat_Code = pn.Panchayat_Code
            LEFT JOIN DDCL_ERP..TblBlock_Master bl ON pn.Block_Code = bl.Block_Code
            LEFT JOIN DDCL_ERP..TblDistrict ds oN bl.District_Code = ds.District_id
            LEFT JOIN DDCL_ERP..TblState_Master st ON st.State_Code = ds.State_id
            LEFT JOIN [Drishtee_stats_new2024].[dbo].tbl_vatika_to_all_mapping_details_new vt ON vt.village_code = v.bhk_village_code  -- vt.physical_vatika_code = v.VatikaId
            WHERE v.VatikaName LIKE ?
          AND st.State_Name = ?
          AND ds.District_name = ?
          '''
        ,
        f"%{csp_vatika}%", state, district
    )
    
    # prod_cursor.execute(query, (f"%{csp_vatika}%", state, district))
    data = prod_cursor.fetchall()

    # Get column names
    columns = [col[0] for col in prod_cursor.description]

    if data:
        for row in data:
            row_dict = dict(zip(columns, row))

            # ✅ Add Excel/group info
            row_dict['input_state'] = state
            row_dict['input_district'] = district
            row_dict['input_vatika'] = csp_vatika

            results.append(row_dict)

    else:
        # If no match found
        results.append({
            'input_state': state,
            'input_district': district,
            'input_vatika': csp_vatika
        })

ASSAM BARPETA Niz Chenga
ASSAM BISWANATH Kalyanpur
ASSAM BONGAIGAON Borigaon
ASSAM BONGAIGAON Dewhati
ASSAM CHARAIDEO BORPATHAR
ASSAM CHARAIDEO HAPEKHATI
ASSAM CHARAIDEO HOLLOWPHUKON
ASSAM CHARAIDEO SAPEKHATI
ASSAM CHARAIDEO SUKAFA
ASSAM CHARAIDEO TENGALIBAM
ASSAM CHIRANG North Salmara
ASSAM DARRANG Demornoi
ASSAM DARRANG Hazarika para
ASSAM DARRANG Niz baruajhar
ASSAM DARRANG Ourala
ASSAM DARRANG lotakat
ASSAM DARRANG niz barauajhar
ASSAM DARRANG niz baruahjar
ASSAM DARRANG no 2 kuwarpukhuri
ASSAM DARRANG no 3 gala dikash
ASSAM DARRANG no 3 galandi kash
ASSAM DARRANG no 3 galndikash
ASSAM DHUBRI Bagmari
ASSAM DHUBRI Bangalipara
ASSAM DHUBRI Barkanda
ASSAM DHUBRI Chapar
ASSAM DHUBRI Falimari
ASSAM DHUBRI Kacharihat
ASSAM DHUBRI Kachukata
ASSAM DHUBRI Kadamtola
ASSAM DHUBRI Lakhiganj
ASSAM DHUBRI Raniganj
ASSAM DIBRUGARH BOKUL
ASSAM DIBRUGARH DIKOM
ASSAM DIBRUGARH Gazpuria
ASSAM DIBRUGARH Hiloidhari
ASSAM DIBRUGARH KHOWANG KHOLOLUA
ASSAM DIBRUGARH MANCOTTA
ASSAM DIBRUGARH MODERKHAT
ASSAM DIBRUGARH Parijat
ASSAM DIBRUGARH Telpani
ASSAM Darrang Sarabari
ASSAM GOALPARA Dariduri
ASSAM GOALPARA Khalichavita
ASSAM GOALPARA Kumri
ASSAM GOALPARA Tukura
ASSAM GOLAGHAT ADARSHA GOMARI GURI
ASSAM GOLAGHAT BILOTIA
ASSAM GOLAGHAT DHEKIAL
ASSAM GOLAGHAT GALABILL
ASSAM GOLAGHAT GAMARIGURI
ASSAM GOLAGHAT GELABIL
ASSAM GOLAGHAT GILADHARI
ASSAM GOLAGHAT KAROIGHAT
ASSAM GOLAGHAT KORAIGHAT
ASSAM GOLAGHAT LETEKUJAN
ASSAM GOLAGHAT MOHARAMUKH
ASSAM GOLAGHAT NOUJAN
ASSAM GOLAGHAT PANJAN
ASSAM GOLAGHAT PHOLONGIA
ASSAM GOLAGHAT POCHIM BORPOTHAR
ASSAM GOLAGHAT PREMHORA
ASSAM GOLAGHAT PUP BORPOTHAR
ASSAM GOLAGHAT SARUPOTHAR
ASSAM GOLAGHAT SENSUWA
ASSAM GOLAGHAT SIMANTA
ASSAM GOLAGHAT TENGA NI
ASSAM GOLAGHAT UTTOR GURU JUGONIA
ASSAM HOJAI 1 no kaki
ASSAM HOJAI Mourajhar(Inactive)
ASSAM HOJAI Rajbari(ina)
ASSAM HOJAI Thaisupar(Inactive)
ASSAM HOJAI ambari
ASSAM HOJAI dimrupar(Inactive)
ASSAM HOJAI kumurakata(ina)
ASSAM JORHAT 71 NO KHONGIA
ASSAM JORHAT BALIGAON
ASSAM JORHAT BIRINASAHEK
ASSAM JORHAT BOKAHULA
ASSAM JORHAT CHUNGI
ASSAM JORHAT DAHIKUR
ASSAM JORHAT GORUMORA
ASSAM JORHAT KACHUKHAT
ASSAM JORHAT KAKOJAN
ASSAM JORHAT LADOIGARH
ASSAM JORHAT MADHAPUR
ASSAM JORHAT RANGAJAN
ASSAM JORHAT SALIKHUWA
ASSAM KAMRUP dohali dokohola
ASSAM KAMRUP pachim chaygaon
ASSAM KAMRUP rampur
ASSAM KAMRUP satpur
ASSAM KAMRUP sualkuchi(ina)
ASSAM KOKRAJHAR Tushpara
ASSAM LAKHIMPUR Azad
ASSAM LAKHIMPUR Chaboti
ASSAM LAKHIMPUR Doolahat sonapur
ASSAM LAKHIMPUR Harhai
ASSAM LAKHIMPUR Pathalipahar
ASSAM MORIGAON bhurbhandha
ASSAM MORIGAON boghora(INA)
ASSAM MORIGAON ghagua(ina)
ASSAM MORIGAON gormari(ina)
ASSAM MORIGAON guva(ina)
ASSAM MORIGAON jagibhakatgaon
ASSAM MORIGAON manipur(ina)
ASSAM MORIGAON salmari(ina)
ASSAM NAGAON Aibheti(Inactive)
ASSAM NAGAON Batamari(Inactive)
ASSAM NAGAON Borbari(Inactive)
ASSAM NAGAON Deudhar
ASSAM NAGAON Phulaguri(Inactive)
ASSAM NAGAON Rangaloo(Inactive)
ASSAM NAGAON dakhin nonoi
ASSAM NAGAON dewdhar
ASSAM NAGAON jamuguri kujidah(ina)
ASSAM NAGAON nizhatichung
ASSAM NAGAON phulaguri(ina)
ASSAM NAGAON puranigudam(Inactive)Brahampur
ASSAM SIVASAGAR ATHABARI
ASSAM SIVASAGAR BORUAHPUKHURI
ASSAM SIVASAGAR Charing
ASSAM SIVASAGAR DEMOW
ASSAM SIVASAGAR DISANGMUKH
ASSAM SIVASAGAR Deuraja
ASSAM SIVASAGAR HAHCHARA
ASSAM SIVASAGAR JOYMOTI
ASSAM SIVASAGAR KHANAMUKH
ASSAM SIVASAGAR LAKUWA
ASSAM SIVASAGAR NITAIPUKHURI
ASSAM SIVASAGAR Nagalamora
ASSAM SIVASAGAR PANBECHA
ASSAM SIVASAGAR PEOLIPHUKON
ASSAM SIVASAGAR RAMONI
ASSAM SIVASAGAR Romoni
ASSAM SIVASAGAR Rudrasagar
ASSAM SIVASAGAR SILAKUTI
ASSAM SIVASAGAR kaiwaimari
ASSAM SIVASAGAR kalibosti
ASSAM SIVASAGAR khelua
ASSAM SIVASAGAR konwarpur
ASSAM SONITPUR Bamunghula
ASSAM SONITPUR Batashipur
ASSAM SONITPUR Belsiri
ASSAM SONITPUR Besseria
ASSAM SONITPUR Bhotpara
ASSAM SONITPUR Borchala
ASSAM SONITPUR Chapai
ASSAM SONITPUR Chitalmari
ASSAM SONITPUR Dolabari
ASSAM SONITPUR Gormara
ASSAM SONITPUR Hugrajuli
ASSAM SONITPUR Khalihamari
ASSAM SONITPUR Lokra`
ASSAM SONITPUR Naharani
ASSAM SONITPUR Panchmile
ASSAM SONITPUR Rangachakua
ASSAM SONITPUR Rowmari
ASSAM SONITPUR Thakurbari
ASSAM SONITPUR Uttar Nagsankar
ASSAM SONITPUR Vitor porua
ASSAM SONITPUR kehurakanda
ASSAM SONITPUR singari
ASSAM TINSUKIA AMBIKAPUR
ASSAM TINSUKIA HOLOGAON
ASSAM TINSUKIA KACHOMARI
ASSAM TINSUKIA KAKOPOTHAR
ASSAM TINSUKIA KAKOPOTHAR ROBORGURI
ASSAM TINSUKIA PANITOLA
ASSAM TINSUKIA RAJGARH
ASSAM UDALGURI balipara
ASSAM UDALGURI dimaruguri
ASSAM UDALGURI gerua
ASSAM UDALGURI jhargaon
ASSAM UDALGURI khoirabari
ASSAM UDALGURI naptipara
ASSAM biswanath Niz sootea
BIHAR BANKA Srinagar
BIHAR BHAGALPUR Akidatpur
MADHYA PRADESH UJJAIN Bhatuni
MADHYA PRADESH UJJAIN Khajjukhedi
MADHYA PRADESH UJJAIN Nanded
MAHARASHTRA AKOLA Ridhora
MAHARASHTRA AMRAVATI Devgaon
MAHARASHTRA AMRAVATI Dhamangaon
MAHARASHTRA AMRAVATI Dhankheda
MAHARASHTRA AMRAVATI Gaurkheda (kumbi)
MAHARASHTRA AMRAVATI Kakda
MAHARASHTRA AMRAVATI Kavitha
MAHARASHTRA BULDHANA Sarolapir
MAHARASHTRA BULDHANA Takarkhed Helga
MAHARASHTRA JALGAON Anapur
MAHARASHTRA JALGAON Anipur
MAHARASHTRA JALGAON Uthkheda ,Abhoda
MAHARASHTRA NAGPUR Methpanjra
MAHARASHTRA NAGPUR Udasa
MAHARASHTRA WARDHA Anji
MAHARASHTRA WARDHA Mahabala
MAHARASHTRA WARDHA Rasulabad
MAHARASHTRA WARDHA Surgaon
MAHARASHTRA YAVATMAL Bori Arab
MAHARASHTRA YAVATMAL Khadka
MAHARASHTRA YAVATMAL Khateshvar
ODISHA BALESHWAR 1.Gopinathpur
2.Bhograi
ODISHA BALESHWAR Nabera
ODISHA BHADRAK Rahania
ODISHA DHENKANAL 1.Mathatentulia
2.Raitala
3.Gundurapasi
4.Sorisiapada
ODISHA DHENKANAL Kerajoli
ODISHA MAYURBHANJ Dugudha
ODISHA MAYURBHANJ Patalipura
ODISHA MAYURBHANJ Sanraikalli
UTTAR PRADESH KHERI  Dhuskia
WEST BENGAL COOCH BEHAR AMBARI
WEST BENGAL COOCH BEHAR CHAKCHAKA
WEST BENGAL COOCH BEHAR KHAPAIDANGA
WEST BENGAL COOCH BEHAR MARICHBARI
WEST BENGAL DAKSHIN DINAJPUR AUTINA
WEST BENGAL DARJEELING KAINJALIA
WEST BENGAL DARJEELING KHARIBARI
WEST BENGAL NADIA Baganchara
WEST BENGAL NORTH 24 PARGANAS Banglani
WEST BENGAL NORTH 24 PARGANAS Bithari Hakimpur
WEST BENGAL NORTH 24 PARGANAS Chandpur
WEST BENGAL NORTH 24 PARGANAS Polerhat
WEST BENGAL SOUTH 24 PARGANAS Benota 1
WEST BENGAL SOUTH 24 PARGANAS Benota 2
WEST BENGAL SOUTH 24 PARGANAS Bhagabanpur
WEST BENGAL SOUTH 24 PARGANAS Daria
WEST BENGAL SOUTH 24 PARGANAS Polerhat
WEST BENGAL SOUTH 24 PARGANAS Shanpukur
WEST BENGAL UTTAR DINAJPUR AMRITA KHANDA , AMRITAKHANDA 2

In [ ]:
prod_cursor.execute(
        '''
            SELECT DISTINCT
            v.VatikaId , v.VatikaName , v.IsDelete, bl.Block_Code , bl.Block_Name
            ,ds.District_id , ds.District_name , st.State_Code , st.State_Name , v.bhk_village_code
            FROM drishtee_vatika..Vatika v
            LEFT JOIN DDCL_ERP..TblVillage_Master vl ON vl.Village_Code = v.VillageId
            LEFT JOIN DDCL_ERP..TblPanchayt_Master pn oN vl.Panchayat_Code = pn.Panchayat_Code
            LEFT JOIN DDCL_ERP..TblBlock_Master bl ON pn.Block_Code = bl.Block_Code
            LEFT JOIN DDCL_ERP..TblDistrict ds oN bl.District_Code = ds.District_id
            LEFT JOIN DDCL_ERP..TblState_Master st ON st.State_Code = ds.State_id
            LEFT JOIN [Drishtee_stats_new2024].[dbo].tbl_vatika_to_all_mapping_details_new vt ON vt.village_code = v.bhk_village_code  -- vt.physical_vatika_code = v.VatikaId
            WHERE v.VatikaName LIKE ?
          AND st.State_Name = ?
          AND ds.District_name = ?
          '''
        ,
        f"%{csp_vatika}%", state, district
    )
    
# prod_cursor.execute(query, (f"%{csp_vatika}%", state, district))
df1 = prod_cursor.fetchall()

# Get column names
columns = [col[0] for col in prod_cursor.description]
rows = [tuple(i) for i in prod_cursor.fetchall()]
df2 = pd.DataFrame.from_records(rows, columns=columns)

In [29]:
results

[{'VatikaId': 6604,
  'VatikaName': 'Niz Chenga',
  'IsDelete': True,
  'Block_Code': 2084,
  'Block_Name': 'Gumla',
  'District_id': 234,
  'District_name': 'Barpeta',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'BARPETA',
  'input_vatika': 'Niz Chenga'},
 {'VatikaId': 6606,
  'VatikaName': 'Niz Chenga',
  'IsDelete': False,
  'Block_Code': 20962,
  'Block_Name': 'Chenga',
  'District_id': 234,
  'District_name': 'Barpeta',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 282988,
  'input_state': 'ASSAM',
  'input_district': 'BARPETA',
  'input_vatika': 'Niz Chenga'},
 {'VatikaId': 6607,
  'VatikaName': 'Niz Chenga',
  'IsDelete': True,
  'Block_Code': 20962,
  'Block_Name': 'Chenga',
  'District_id': 234,
  'District_name': 'Barpeta',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 1000557,
  'input_state': 'ASSAM',
  'input_district': 'BARPETA',
  'input_vatika': 'Niz Chenga'},
 {'VatikaId': 6432,
  'VatikaName': 'Niz Chenga Vatika',
  'IsDelete': True,
  'Block_Code': 20962,
  'Block_Name': 'Chenga',
  'District_id': 234,
  'District_name': 'Barpeta',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'BARPETA',
  'input_vatika': 'Niz Chenga'},
 {'VatikaId': 6433,
  'VatikaName': 'Niz Chenga',
  'IsDelete': True,
  'Block_Code': 20962,
  'Block_Name': 'Chenga',
  'District_id': 234,
  'District_name': 'Barpeta',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'BARPETA',
  'input_vatika': 'Niz Chenga'},
 {'VatikaId': 6434,
  'VatikaName': 'Niz Chenga',
  'IsDelete': True,
  'Block_Code': 20962,
  'Block_Name': 'Chenga',
  'District_id': 234,
  'District_name': 'Barpeta',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'BARPETA',
  'input_vatika': 'Niz Chenga'},
 {'VatikaId': 6452,
  'VatikaName': 'Niz Chenga Vatila',
  'IsDelete': True,
  'Block_Code': 20962,
  'Block_Name': 'Chenga',
  'District_id': 234,
  'District_name': 'Barpeta',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'BARPETA',
  'input_vatika': 'Niz Chenga'},
 {'VatikaId': 6435,
  'VatikaName': 'Niz Chenga',
  'IsDelete': True,
  'Block_Code': 20962,
  'Block_Name': 'Chenga',
  'District_id': 234,
  'District_name': 'Barpeta',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'BARPETA',
  'input_vatika': 'Niz Chenga'},
 {'input_state': 'ASSAM',
  'input_district': 'BISWANATH',
  'input_vatika': 'Kalyanpur'},
 {'VatikaId': 6337,
  'VatikaName': 'Borigaon',
  'IsDelete': True,
  'Block_Code': 16822,
  'Block_Name': 'Tapattary',
  'District_id': 336,
  'District_name': 'Bongaigaon',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 301513,
  'input_state': 'ASSAM',
  'input_district': 'BONGAIGAON',
  'input_vatika': 'Borigaon'},
 {'VatikaId': 6847,
  'VatikaName': 'Borigaon',
  'IsDelete': False,
  'Block_Code': 16822,
  'Block_Name': 'Tapattary',
  'District_id': 336,
  'District_name': 'Bongaigaon',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 301513,
  'input_state': 'ASSAM',
  'input_district': 'BONGAIGAON',
  'input_vatika': 'Borigaon'},
 {'input_state': 'ASSAM',
  'input_district': 'BONGAIGAON',
  'input_vatika': 'Dewhati'},
 {'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'BORPATHAR'},
 {'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'HAPEKHATI'},
 {'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'HOLLOWPHUKON'},
 {'VatikaId': 15201,
  'VatikaName': 'Sapekhati ',
  'IsDelete': False,
  'Block_Code': 22077,
  'Block_Name': 'Sapekhati',
  'District_id': 2288,
  'District_name': 'Charaideo',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 1000024,
  'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'SAPEKHATI'},
 {'VatikaId': 12442,
  'VatikaName': 'Sapekhati ',
  'IsDelete': True,
  'Block_Code': 22077,
  'Block_Name': 'Sapekhati',
  'District_id': 2288,
  'District_name': 'Charaideo',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'SAPEKHATI'},
 {'VatikaId': 12443,
  'VatikaName': 'Sapekhati ',
  'IsDelete': True,
  'Block_Code': 22077,
  'Block_Name': 'Sapekhati',
  'District_id': 2288,
  'District_name': 'Charaideo',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'SAPEKHATI'},
 {'VatikaId': 12444,
  'VatikaName': 'Sapekhati ',
  'IsDelete': True,
  'Block_Code': 22077,
  'Block_Name': 'Sapekhati',
  'District_id': 2288,
  'District_name': 'Charaideo',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'SAPEKHATI'},
 {'VatikaId': 12447,
  'VatikaName': 'Sapekhati',
  'IsDelete': False,
  'Block_Code': 22077,
  'Block_Name': 'Sapekhati',
  'District_id': 2288,
  'District_name': 'Charaideo',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 1000024,
  'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'SAPEKHATI'},
 {'VatikaId': 12449,
  'VatikaName': 'Sapekhati',
  'IsDelete': True,
  'Block_Code': 22077,
  'Block_Name': 'Sapekhati',
  'District_id': 2288,
  'District_name': 'Charaideo',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'SAPEKHATI'},
 {'VatikaId': 12450,
  'VatikaName': 'Sapekhati',
  'IsDelete': True,
  'Block_Code': 22077,
  'Block_Name': 'Sapekhati',
  'District_id': 2288,
  'District_name': 'Charaideo',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 1000024,
  'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'SAPEKHATI'},
 {'VatikaId': 12401,
  'VatikaName': 'SUKAFA VATIKA ',
  'IsDelete': False,
  'Block_Code': 20998,
  'Block_Name': 'Mahmora',
  'District_id': 2288,
  'District_name': 'Charaideo',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 1000023,
  'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'SUKAFA'},
 {'input_state': 'ASSAM',
  'input_district': 'CHARAIDEO',
  'input_vatika': 'TENGALIBAM'},
 {'input_state': 'ASSAM',
  'input_district': 'CHIRANG',
  'input_vatika': 'North Salmara'},
 {'input_state': 'ASSAM',
  'input_district': 'DARRANG',
  'input_vatika': 'Demornoi'},
 {'input_state': 'ASSAM',
  'input_district': 'DARRANG',
  'input_vatika': 'Hazarika para'},
 {'input_state': 'ASSAM',
  'input_district': 'DARRANG',
  'input_vatika': 'Niz baruajhar'},
 {'input_state': 'ASSAM',
  'input_district': 'DARRANG',
  'input_vatika': 'Ourala'},
 {'input_state': 'ASSAM',
  'input_district': 'DARRANG',
  'input_vatika': 'lotakat'},
 {'input_state': 'ASSAM',
  'input_district': 'DARRANG',
  'input_vatika': 'niz barauajhar'},
 {'input_state': 'ASSAM',
  'input_district': 'DARRANG',
  'input_vatika': 'niz baruahjar'},
 {'input_state': 'ASSAM',
  'input_district': 'DARRANG',
  'input_vatika': 'no 2 kuwarpukhuri'},
 {'input_state': 'ASSAM',
  'input_district': 'DARRANG',
  'input_vatika': 'no 3 gala dikash'},
 {'input_state': 'ASSAM',
  'input_district': 'DARRANG',
  'input_vatika': 'no 3 galandi kash'},
 {'input_state': 'ASSAM',
  'input_district': 'DARRANG',
  'input_vatika': 'no 3 galndikash'},
 {'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Bagmari'},
 {'VatikaId': 6446,
  'VatikaName': 'Anandanagar-Bangalipara',
  'IsDelete': True,
  'Block_Code': 16868,
  'Block_Name': 'Bilasipara',
  'District_id': 515,
  'District_name': 'Dhubri',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Bangalipara'},
 {'VatikaId': 6716,
  'VatikaName': 'Bangalipara ',
  'IsDelete': True,
  'Block_Code': 16868,
  'Block_Name': 'Bilasipara',
  'District_id': 515,
  'District_name': 'Dhubri',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 281327,
  'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Bangalipara'},
 {'VatikaId': 6723,
  'VatikaName': 'Bangalipara',
  'IsDelete': False,
  'Block_Code': 16868,
  'Block_Name': 'Bilasipara',
  'District_id': 515,
  'District_name': 'Dhubri',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 281327,
  'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Bangalipara'},
 {'VatikaId': 6440,
  'VatikaName': 'Barkanda',
  'IsDelete': True,
  'Block_Code': 7739,
  'Block_Name': 'Mahamaya',
  'District_id': 515,
  'District_name': 'Dhubri',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Barkanda'},
 {'VatikaId': 6441,
  'VatikaName': 'Barkanda',
  'IsDelete': True,
  'Block_Code': 7739,
  'Block_Name': 'Mahamaya',
  'District_id': 515,
  'District_name': 'Dhubri',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Barkanda'},
 {'VatikaId': 6444,
  'VatikaName': 'Barkanda',
  'IsDelete': True,
  'Block_Code': 7739,
  'Block_Name': 'Mahamaya',
  'District_id': 515,
  'District_name': 'Dhubri',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Barkanda'},
 {'VatikaId': 6555,
  'VatikaName': 'Barkanda',
  'IsDelete': False,
  'Block_Code': 7739,
  'Block_Name': 'Mahamaya',
  'District_id': 515,
  'District_name': 'Dhubri',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 281235,
  'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Barkanda'},
 {'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Chapar'},
 {'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Falimari'},
 {'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Kacharihat'},
 {'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Kachukata'},
 {'VatikaId': 6746,
  'VatikaName': 'Kadamtola',
  'IsDelete': False,
  'Block_Code': 20960,
  'Block_Name': 'Nayeralga',
  'District_id': 515,
  'District_name': 'Dhubri',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 281244,
  'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Kadamtola'},
 {'VatikaId': 6547,
  'VatikaName': 'Lakhiganj',
  'IsDelete': False,
  'Block_Code': 16868,
  'Block_Name': 'Bilasipara',
  'District_id': 515,
  'District_name': 'Dhubri',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 281302,
  'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Lakhiganj'},
 {'VatikaId': 14799,
  'VatikaName': 'Lakhiganj',
  'IsDelete': True,
  'Block_Code': 16868,
  'Block_Name': 'Bilasipara',
  'District_id': 515,
  'District_name': 'Dhubri',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 281302,
  'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Lakhiganj'},
 {'VatikaId': 6504,
  'VatikaName': 'Raniganj',
  'IsDelete': False,
  'Block_Code': 16868,
  'Block_Name': 'Bilasipara',
  'District_id': 515,
  'District_name': 'Dhubri',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 281314,
  'input_state': 'ASSAM',
  'input_district': 'DHUBRI',
  'input_vatika': 'Raniganj'},
 {'VatikaId': 6276,
  'VatikaName': 'Bokul ',
  'IsDelete': False,
  'Block_Code': 7734,
  'Block_Name': 'Lahoal',
  'District_id': 521,
  'District_name': 'Dibrugarh',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 1000043,
  'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'BOKUL'},
 {'VatikaId': 7980,
  'VatikaName': 'Dikom',
  'IsDelete': True,
  'Block_Code': 22070,
  'Block_Name': 'Panitola',
  'District_id': 521,
  'District_name': 'Dibrugarh',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'DIKOM'},
 {'VatikaId': 7984,
  'VatikaName': 'Dikom',
  'IsDelete': False,
  'Block_Code': 22070,
  'Block_Name': 'Panitola',
  'District_id': 521,
  'District_name': 'Dibrugarh',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 291413,
  'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'DIKOM'},
 {'VatikaId': 6588,
  'VatikaName': 'Gazpuria',
  'IsDelete': False,
  'Block_Code': 20981,
  'Block_Name': 'Khowang',
  'District_id': 521,
  'District_name': 'Dibrugarh',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 1000039,
  'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'Gazpuria'},
 {'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'Hiloidhari'},
 {'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'KHOWANG KHOLOLUA'},
 {'VatikaId': 6487,
  'VatikaName': 'Mancotta',
  'IsDelete': False,
  'Block_Code': 16903,
  'Block_Name': 'Barbaruah',
  'District_id': 521,
  'District_name': 'Dibrugarh',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 1000036,
  'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'MANCOTTA'},
 {'VatikaId': 14735,
  'VatikaName': 'Moderkhat',
  'IsDelete': False,
  'Block_Code': 7734,
  'Block_Name': 'Lahoal',
  'District_id': 521,
  'District_name': 'Dibrugarh',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 291326,
  'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'MODERKHAT'},
 {'VatikaId': 14736,
  'VatikaName': 'Moderkhat',
  'IsDelete': True,
  'Block_Code': 7734,
  'Block_Name': 'Lahoal',
  'District_id': 521,
  'District_name': 'Dibrugarh',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'MODERKHAT'},
 {'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'Parijat'},
 {'VatikaId': 6832,
  'VatikaName': 'Telpani ',
  'IsDelete': True,
  'Block_Code': 21028,
  'Block_Name': 'Tengakhat',
  'District_id': 521,
  'District_name': 'Dibrugarh',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'Telpani'},
 {'VatikaId': 6833,
  'VatikaName': 'Telpani ',
  'IsDelete': True,
  'Block_Code': 21028,
  'Block_Name': 'Tengakhat',
  'District_id': 521,
  'District_name': 'Dibrugarh',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': None,
  'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'Telpani'},
 {'VatikaId': 6838,
  'VatikaName': 'Telpani',
  'IsDelete': False,
  'Block_Code': 21028,
  'Block_Name': 'Tengakhat',
  'District_id': 521,
  'District_name': 'Dibrugarh',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 291641,
  'input_state': 'ASSAM',
  'input_district': 'DIBRUGARH',
  'input_vatika': 'Telpani'},
 {'VatikaId': 6550,
  'VatikaName': 'Sarabari',
  'IsDelete': False,
  'Block_Code': 16831,
  'Block_Name': 'Sipajhar',
  'District_id': 466,
  'District_name': 'Darrang',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 304840,
  'input_state': 'ASSAM',
  'input_district': 'Darrang',
  'input_vatika': 'Sarabari'},
 {'VatikaId': 6442,
  'VatikaName': 'Dariduri ',
  'IsDelete': True,
  'Block_Code': 20964,
  'Block_Name': 'Balijana',
  'District_id': 632,
  'District_name': 'Goalpara',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 282066,
  'input_state': 'ASSAM',
  'input_district': 'GOALPARA',
  'input_vatika': 'Dariduri'},
 {'VatikaId': 6593,
  'VatikaName': 'Dariduri Vatika',
  'IsDelete': False,
  'Block_Code': 20964,
  'Block_Name': 'Balijana',
  'District_id': 632,
  'District_name': 'Goalpara',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 282117,
  'input_state': 'ASSAM',
  'input_district': 'GOALPARA',
  'input_vatika': 'Dariduri'},
 {'VatikaId': 6743,
  'VatikaName': 'Dariduri Vatika ',
  'IsDelete': True,
  'Block_Code': 20964,
  'Block_Name': 'Balijana',
  'District_id': 632,
  'District_name': 'Goalpara',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 282117,
  'input_state': 'ASSAM',
  'input_district': 'GOALPARA',
  'input_vatika': 'Dariduri'},
 {'input_state': 'ASSAM',
  'input_district': 'GOALPARA',
  'input_vatika': 'Khalichavita'},
 {'VatikaId': 14726,
  'VatikaName': 'Kumri Vatika',
  'IsDelete': False,
  'Block_Code': 20964,
  'Block_Name': 'Balijana',
  'District_id': 632,
  'District_name': 'Goalpara',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 282124,
  'input_state': 'ASSAM',
  'input_district': 'GOALPARA',
  'input_vatika': 'Kumri'},
 {'VatikaId': 10196,
  'VatikaName': 'Tukura Vatika',
  'IsDelete': False,
  'Block_Code': 23122,
  'Block_Name': 'krishnai',
  'District_id': 632,
  'District_name': 'Goalpara',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 282353,
  'input_state': 'ASSAM',
  'input_district': 'GOALPARA',
  'input_vatika': 'Tukura'},
 {'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'ADARSHA GOMARI GURI'},
 {'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'BILOTIA'},
 {'VatikaId': 12553,
  'VatikaName': 'Dhekial',
  'IsDelete': False,
  'Block_Code': 20946,
  'Block_Name': 'Golaghat Central',
  'District_id': 642,
  'District_name': 'Golaghat',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 294566,
  'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'DHEKIAL'},
 {'VatikaId': 12335,
  'VatikaName': 'Dhekial',
  'IsDelete': True,
  'Block_Code': 20946,
  'Block_Name': 'Golaghat Central',
  'District_id': 642,
  'District_name': 'Golaghat',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 294566,
  'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'DHEKIAL'},
 {'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'GALABILL'},
 {'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'GAMARIGURI'},
 {'VatikaId': 6868,
  'VatikaName': 'Gelabil',
  'IsDelete': False,
  'Block_Code': 6685,
  'Block_Name': 'Sarupathar',
  'District_id': 642,
  'District_name': 'Golaghat',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 1000069,
  'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'GELABIL'},
 {'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'GILADHARI'},
 {'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'KAROIGHAT'},
 {'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'KORAIGHAT'},
 {'VatikaId': 6377,
  'VatikaName': 'Letekujan Grant',
  'IsDelete': False,
  'Block_Code': 8792,
  'Block_Name': 'Morongi',
  'District_id': 642,
  'District_name': 'Golaghat',
  'State_Code': 4,
  'State_Name': 'Assam',
  'bhk_village_code': 294782,
  'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'LETEKUJAN'},
 {'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'MOHARAMUKH'},
 {'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'NOUJAN'},
 {'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'PANJAN'},
 {'input_state': 'ASSAM',
  'input_district': 'GOLAGHAT',
  'input_vatika': 'PHOLONGIA'},

In [ ]:
query_df = pd.DataFrame(results)

Index(['VatikaId', 'VatikaName', 'IsDelete', 'Block_Code', 'Block_Name',
       'District_id', 'District_name', 'State_Code', 'State_Name',
       'bhk_village_code', 'input_state', 'input_district', 'input_vatika'],
      dtype='object')

In [31]:
query_df

,VatikaId,VatikaName,IsDelete,Block_Code,Block_Name,District_id,District_name,State_Code,State_Name,bhk_village_code,input_state,input_district,input_vatika
0,6604.0,Niz Chenga,True,2084.0,Gumla,234.0,Barpeta,4.0,Assam,NaN,ASSAM,BARPETA,Niz Chenga
1,6606.0,Niz Chenga,False,20962.0,Chenga,234.0,Barpeta,4.0,Assam,282988.0,ASSAM,BARPETA,Niz Chenga
2,6607.0,Niz Chenga,True,20962.0,Chenga,234.0,Barpeta,4.0,Assam,1000557.0,ASSAM,BARPETA,Niz Chenga
3,6432.0,Niz Chenga Vatika,True,20962.0,Chenga,234.0,Barpeta,4.0,Assam,NaN,ASSAM,BARPETA,Niz Chenga
4,6433.0,Niz Chenga,True,20962.0,Chenga,234.0,Barpeta,4.0,Assam,NaN,ASSAM,BARPETA,Niz Chenga
...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WEST BENGAL,SOUTH 24 PARGANAS,Bhagabanpur
281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WEST BENGAL,SOUTH 24 PARGANAS,Daria
282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WEST BENGAL,SOUTH 24 PARGANAS,Polerhat
283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WEST BENGAL,SOUTH 24 PARGANAS,Shanpukur
284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WEST BENGAL,UTTAR DINAJPUR,"AMRITA KHANDA , AMRITAKHANDA 2"

In [32]:
query_df.to_excel('CSP_BHK_VATIKA.xlsx')

# Connecting through Json Key

In [4]:
# Path to your downloaded key
service_acc_key = os.getenv("gcp_bot_key")

# Define the required scopes
SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    # "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/drive.readonly"
]

# Authorize
creds = Credentials.from_service_account_file(service_acc_key, scopes=SCOPES)
gc = gspread.authorize(creds)

In [65]:
# sheet_url = 'https://docs.google.com/spreadsheets/d/1SKgKmXeInkKkhEB4eIj0bEBMXel-fvYEnqe4n7OE1hc/edit?pli=1&gid=0#gid=0'

# sh = gc.open_by_url(sheet_url) # Stores Whole Google Sheet as an Object


* **sh.title**   # returns "Title" 
* **sh.worksheets()**  # returns a list of all sheet objects inside this file
# worksheet = sh.worksheet("Sheet1")
* **worksheet.title**  # 'Sheet1'
* **worksheet.row_count**  # total number of rows
* **worksheet.col_count**  # total number of columns
* **worksheet.get_all_records()**  # returns list of dicts for all rows

In [7]:
# sheetName = sh.worksheet('Sheet1')

# ld = sheetName.get_all_records() # List of Dictionaries
# df = pd.DataFrame(ld) # Converting List of Dictionaries to DataFrame
# df

# OR

In [15]:
# df2 = get_as_dataframe(sheetName, evaluate_formulas=True, header=0)
# df2

# Bulk Insert def

In [16]:
def bulk_insert(table_name, data, batch_size , cursor):
    try:
        columns = data.columns.tolist()
        # columns_str = ', '.join(columns)
        columns_str = ', '.join([f'[{col}]' for col in columns])
        placeholders = ', '.join(['?' for _ in range(len(columns))])
        insert_query = f"INSERT INTO WAVE..{table_name} ({columns_str}) VALUES ({placeholders})"
        
        total_inserted = 0
        
        # Process in batches
        for i in range(0, len(data), batch_size):
            batch = data.iloc[i: i + batch_size]
            records = [tuple(row) for _, row in batch.iterrows()]
            
            print(f"Executing batch insert for records {i} to {i + len(records) - 1}")
            cursor.executemany(insert_query, records)
            
            total_inserted += len(records) 
            print(f"Inserted batch: {total_inserted}/{len(data)} records")
                
        
        print(f"✓ Successfully inserted all {total_inserted} records into {table_name}")
        cursor.connection.commit()
        # conn.close()
        
    except Exception as e:
        # conn.rollback()
        print(f"✗ Error inserting data: {str(e)}")
        
    # finally:
    #     warehouse_cursor.close()
    #     conn.close()

# CSP List / CSP Master

In [5]:
csp_list_url = 'https://docs.google.com/spreadsheets/d/1rVg5FKcyeg1Df4oUdc6ak-wka_YO4e8Gxs_FBexK5LU/edit?gid=0#gid=0'
csp_sheet = gc.open_by_url(csp_list_url)

In [8]:
csp_sheet.worksheets()

# Converting into DataFrame

In [6]:
csp_df = pd.DataFrame(csp_sheet.worksheet('Sheet1').get_all_records())
csp_df

,BANK,CSPCODE,CSP Name,State,Territory,District,BLOCK,Branch,PINCODE,Code Creation Date,...,Vatika ID,Vatika Name,Status,Refund Amount,Licence_Fee_Refund_Date,Employee\nMapped,Gender,Location Type,Tenure,Productive\nStatus
0,BOB,11710778,Jitesh Agrawal,Dadra And Nagar Haveli,Virtual Terr_Dadra And Nagar Haveli,Dadra And Nagar Haveli,Silvassa,Silvassa Vapi Mail Road,396230,2022-02-03,...,,NA,Active,,,Rahul Sain,M,URBAN,4.0,Active
1,BOB,11710813,Mahla Monalikumari Gulabbhai,Dadra And Nagar Haveli,Virtual Terr_Dadra And Nagar Haveli,Dadra And Nagar Haveli,Dadarand Nagar Haveli,Kilavani,396230,2022-02-03,...,,NA,Replacement,,,Rahul Sain,M,RURAL,4.0,
2,BOB,11710694,Abhinavkumar Rushabhkumar Yagnik,Gujarat,Virtual Terr_Gujarat,Ahmadabad,Vastral,"Naroda Road, Ahmedabad",,2022-03-31,...,,NA,Replacement,,,,M,,3.9,
3,BOB,11710706,Divyaben Nepubhai Makwana,Gujarat,Virtual Terr_Gujarat,Ahmadabad,bavla,Bavla,,2022-03-31,...,,NA,Replacement,,,,F,,3.9,
4,BOB,11710652,Mohasinbhai Ishakbhai Chandi,Gujarat,Virtual Terr_Gujarat,Ahmadabad,Ghanchiwada,Meghraj,383350,2022-02-01,...,,NA,Active,,,Rahul Sain,M,URBAN,4.0,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4463,PNB,K3800727,Ramandeep Kaur,Punjab,Virtual,Amritsar,,,,2026-01-23,...,,,Active,,,,,,0.0,Active
4464,SBI,10020410,Bimal Tanti,Assam,Sivsagar,Golaghat,,,,2026-01-23,...,,,Active,,,,,,0.0,
4465,SBI,10022629,Ajmot Ali,Assam,Dhubri,Kokrajhar,,,,2026-01-23,...,,,Active,,,,,,0.0,
4466,BOB,11711238,Mahendra Kumar,Uttar Pradesh,Virtual,Kaushambi,,,,2026-01-22,...,,,Active,,,,,,0.0,Active
4467,PNB,K3800763,Kirpal Singh,Jammu And Kashmir,Virtual,Udhampur,,,,2026-01-21,...,,,Active,,,,,,0.0,Active

In [7]:
warehouse_cursor.execute("SELECT * FROM WAVE..CSP_Master")

rows_tuple = [tuple(i) for i in warehouse_cursor.fetchall()]

column = [column[0] for column in warehouse_cursor.description]

csp_master_df = pd.DataFrame(rows_tuple, columns=column)
csp_master_df

,BANK,CSPCODE,CSP_Name,Key,State,Territory,District,BLOCK,bhk_block_code,Status,...,Vatika_Name,MATM_PINPAD,GPS_Dongle,Refund_Amount,Licence_Fee_Refund_Date,Employee_Mapped,Gender,Location_Type,Tenure,Productive_Status
0,BOB,11710778,Jitesh Agrawal,,Dadra And Nagar Haveli,Virtual Terr_Dadra And Nagar Haveli,Dadra And Nagar Haveli,Silvassa,0,Active,...,NA,None,None,None,None,None,None,None,None,None
1,BOB,11710813,Mahla Monalikumari Gulabbhai,,Dadra And Nagar Haveli,Virtual Terr_Dadra And Nagar Haveli,Dadra And Nagar Haveli,Dadarand Nagar Haveli,0,Replacement,...,NA,None,None,None,None,None,None,None,None,None
2,BOB,11710694,Abhinavkumar Rushabhkumar Yagnik,,Gujarat,Virtual Terr_Gujarat,Ahmadabad,Vastral,0,Replacement,...,NA,None,None,None,None,None,None,None,None,None
3,BOB,11710706,Divyaben Nepubhai Makwana,,Gujarat,Virtual Terr_Gujarat,Ahmadabad,bavla,0,Replacement,...,NA,None,None,None,None,None,None,None,None,None
4,BOB,11710652,Mohasinbhai Ishakbhai Chandi,,Gujarat,Virtual Terr_Gujarat,Ahmadabad,Ghanchiwada,0,Active,...,NA,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4463,PNB,K3800727,Ramandeep Kaur,,Punjab,Virtual,Amritsar,,0,Active,...,,None,None,None,None,None,None,None,None,None
4464,SBI,10020410,Bimal Tanti,,Assam,Sivsagar,Golaghat,,0,Active,...,,None,None,None,None,None,None,None,None,None
4465,SBI,10022629,Ajmot Ali,,Assam,Dhubri,Kokrajhar,,0,Active,...,,None,None,None,None,None,None,None,None,None
4466,BOB,11711238,Mahendra Kumar,,Uttar Pradesh,Virtual,Kaushambi,,0,Active,...,,None,None,None,None,None,None,None,None,None
4467,PNB,K3800763,Kirpal Singh,,Jammu And Kashmir,Virtual,Udhampur,,0,Active,...,,None,None,None,None,None,None,None,None,None

# Transformation

In [8]:
csp_df.columns.tolist , csp_master_df.columns.tolist

(<bound method IndexOpsMixin.tolist of Index(['BANK', 'CSPCODE', 'CSP Name', 'State', 'Territory', 'District',
        'BLOCK', 'Branch', 'PINCODE', 'Code Creation Date', 'Agreement Date',
        'Agreement Renewal Date', 'IIBF Certificate\nNumber', 'Printer',
        'MATM/PINPAD', 'GPS-Dongle', 'Licence Fee\n Amount', 'MR Date',
        'MR No.', 'Received Amount', 'Vatika ID', 'Vatika Name', 'Status',
        'Refund Amount', 'Licence_Fee_Refund_Date', 'Employee\nMapped',
        'Gender', 'Location Type', 'Tenure', 'Productive\nStatus'],
       dtype='object')>,
 <bound method IndexOpsMixin.tolist of Index(['BANK', 'CSPCODE', 'CSP_Name', 'Key', 'State', 'Territory', 'District',
        'BLOCK', 'bhk_block_code', 'Status', 'Branch', 'PINCODE',
        'Code_Creation_Date', 'Agreement_Date', 'Agreement_Renewal_Date',
        'IIBF_Certificate_Number', 'Printer', 'MATM', 'PinPad',
        'Licence_Fee_Amount', 'MR_Date', 'MR_No', 'Received_Amount',
        'Vatika_ID', 'Vatika_Name', 'MATM_PINPAD', 'GPS_Dongle',
        'Refund_Amount', 'Licence_Fee_Refund_Date', 'Employee_Mapped', 'Gender',
        'Location_Type', 'Tenure', 'Productive_Status'],
       dtype='object')>)

# Replacing Null Values

In [9]:
csp_df['PINCODE'] = pd.to_numeric(csp_df['PINCODE'], errors='coerce').fillna(0).astype('int')
# csp_df['MATM'] = pd.to_numeric(csp_df['MATM'], errors='coerce').fillna(0).astype('int')
# csp_df['PinPad'] = pd.to_numeric(csp_df['PinPad'], errors='coerce').fillna(0).astype('int')
csp_df['Vatika ID'] = pd.to_numeric(csp_df['Vatika ID'], errors='coerce').fillna(0).astype('int')
csp_df['MR No.'] = pd.to_numeric(csp_df['MR No.'], errors='coerce').fillna(0).astype('int')
csp_df['Licence Fee\n Amount'] = pd.to_numeric(csp_df['Licence Fee\n Amount'], errors='coerce').fillna(0.0)
csp_df['Received Amount'] = pd.to_numeric(csp_df['Received Amount'], errors='coerce').fillna(0.0)
csp_df['Refund Amount'] = pd.to_numeric(csp_df['Refund Amount'], errors='coerce').fillna(0.0)
csp_df['Tenure'] = pd.to_numeric(csp_df['Tenure'], errors='coerce').fillna(0.0)

In [10]:
#  'Vatika Name', 'Status',
#        'Refund Amount', 'Licence_Fee_Refund_Date', 'Employee\nMapped',
#        'Gender', 'Location Type']

fill_values = {
    'BANK': "",
    'CSPCODE': "",
    'CSP Name': "",
    'Key': "",
    'State': "",
    'Territory': "",
    'District': "",
    'BLOCK': "",
    'Status': "",
    'Branch': "",
    'Code Creation Date': '1999-01-01',        # keep datetime Null
    'Agreement Date': '1999-01-01',
    'Agreement Renewal Date': '1999-01-01',
    'IIBF Certificate\nNumber': "",
    'Printer': "",
    'MR Date': '1999-01-01',
    'Vatika Name': "",
    'Licence_Fee_Refund_Date': '1999-01-01',
    'Employee\nMapped': "",
    'Gender': "",
    'Location Type': "",
    'Productive\nStatus': "",
}

for col, default_value in fill_values.items():
    if col in csp_df.columns:
        csp_df[col] = csp_df[col].fillna(default_value)

In [11]:
csp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4468 entries, 0 to 4467
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   BANK                     4468 non-null   object
 1   CSPCODE                  4468 non-null   object
 2   CSP Name                 4468 non-null   object
 3   State                    4468 non-null   object
 4   Territory                4468 non-null   object
 5   District                 4468 non-null   object
 6   BLOCK                    4468 non-null   object
 7   Branch                   4468 non-null   object
 8   PINCODE                  4468 non-null   int32
 9   Code Creation Date       4468 non-null   object
 10  Agreement Date           4468 non-null   object
 11  Agreement Renewal Date   4468 non-null   object
 12  IIBF Certificate
Number  4468 non-null   object
 13  Printer                  4468 non-null   object
 14  MATM/PINPAD              4468 non-null   object
 15  GPS-Dongle               4468 non-null   object
 16  Licence Fee
 Amount      4468 non-null   float64
 17  MR Date                  4468 non-null   object
 18  MR No.                   4468 non-null   int32
 19  Received Amount          4468 non-null   float64
 20  Vatika ID                4468 non-null   int32
 21  Vatika Name              4468 non-null   object
 22  Status                   4468 non-null   object
 23  Refund Amount            4468 non-null   float64
 24  Licence_Fee_Refund_Date  4468 non-null   object
 25  Employee
Mapped          4468 non-null   object
 26  Gender                   4468 non-null   object
 27  Location Type            4468 non-null   object
 28  Tenure                   4468 non-null   float64
 29  Productive
Status        4468 non-null   object
dtypes: float64(4), int32(3), object(23)
memory usage: 995.0+ KB

# Correcting Datatypes

In [12]:
dtype_map = {
    'BANK': 'object',
    'CSPCODE': 'object',
    'CSP Name': 'object',
    'Key': 'object',
    'State': 'object',
    'Territory': 'object',
    'District': 'object',
    'BLOCK': 'object',
    'Status': 'object',
    'Branch': 'object',
    'PINCODE': 'int',
    'Code Creation Date': 'datetime64[ns]',
    'Agreement Date': 'datetime64[ns]',
    'Agreement Renewal Date': 'datetime64[ns]',
    'IIBF Certificate\nNumber': 'object',
    'Printer': 'object',
    'Licence_Fee_Refund_Date': 'datetime64[ns]',
    # 'MATM': 'int',
    # 'PinPad': 'int',
    'Licence Fee\n Amount': 'float',
    'MR Date': 'datetime64[ns]',
    'MR No': 'int',
    'Received Amount': 'float',
    'Vatika ID': 'int',
    'Vatika Name': 'object'
}

# Apply safe conversions
for col, new_type in dtype_map.items():
    if col in csp_df.columns:
        try:
            if "datetime" in new_type:
                csp_df[col] = pd.to_datetime(csp_df[col], errors='coerce')
            else:
                csp_df[col] = csp_df[col].astype(new_type)
        except Exception as e:
            print(f"Datatype conversion failed for {col}: {e}")

In [13]:
csp_df['Code Creation Date'] = pd.to_datetime(csp_df['Code Creation Date'])
csp_df['Agreement Date'] = pd.to_datetime(csp_df['Agreement Date'])
csp_df['Agreement Renewal Date'] = pd.to_datetime(csp_df['Agreement Renewal Date'])
# csp_df['Licence Fee Refund Date'] = pd.to_datetime(csp_df['Licence Fee Refund Date'])
csp_df['MR Date'] = pd.to_datetime(csp_df['MR Date'])
# csp_df['Licence Fee Amount'] = csp_df['Licence Fee Amount'].astype('float')
csp_df['Received Amount'] = csp_df['Received Amount'].astype('float') 
csp_df['Vatika ID'] = csp_df['Vatika ID'].astype('int')
csp_df['Licence_Fee_Refund_Date'] = pd.to_datetime(csp_df['Licence_Fee_Refund_Date'], errors='coerce')

In [15]:
# [f"{i} - {csp_df[i].dtype}" for i in csp_df.columns]
# print([f"{i} - {csp_master_df[i].dtype}" for i in csp_master_df.columns])

In [14]:
csp_df['CSPCODE'] = csp_df['CSPCODE'].astype(str).str.strip()
csp_master_df['CSPCODE'] = csp_master_df['CSPCODE'].astype(str).str.strip()

In [15]:
csp_df

,BANK,CSPCODE,CSP Name,State,Territory,District,BLOCK,Branch,PINCODE,Code Creation Date,...,Vatika ID,Vatika Name,Status,Refund Amount,Licence_Fee_Refund_Date,Employee\nMapped,Gender,Location Type,Tenure,Productive\nStatus
0,BOB,11710778,Jitesh Agrawal,Dadra And Nagar Haveli,Virtual Terr_Dadra And Nagar Haveli,Dadra And Nagar Haveli,Silvassa,Silvassa Vapi Mail Road,396230,2022-02-03,...,0,NA,Active,0.0,NaT,Rahul Sain,M,URBAN,4.0,Active
1,BOB,11710813,Mahla Monalikumari Gulabbhai,Dadra And Nagar Haveli,Virtual Terr_Dadra And Nagar Haveli,Dadra And Nagar Haveli,Dadarand Nagar Haveli,Kilavani,396230,2022-02-03,...,0,NA,Replacement,0.0,NaT,Rahul Sain,M,RURAL,4.0,
2,BOB,11710694,Abhinavkumar Rushabhkumar Yagnik,Gujarat,Virtual Terr_Gujarat,Ahmadabad,Vastral,"Naroda Road, Ahmedabad",0,2022-03-31,...,0,NA,Replacement,0.0,NaT,,M,,3.9,
3,BOB,11710706,Divyaben Nepubhai Makwana,Gujarat,Virtual Terr_Gujarat,Ahmadabad,bavla,Bavla,0,2022-03-31,...,0,NA,Replacement,0.0,NaT,,F,,3.9,
4,BOB,11710652,Mohasinbhai Ishakbhai Chandi,Gujarat,Virtual Terr_Gujarat,Ahmadabad,Ghanchiwada,Meghraj,383350,2022-02-01,...,0,NA,Active,0.0,NaT,Rahul Sain,M,URBAN,4.0,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4463,PNB,K3800727,Ramandeep Kaur,Punjab,Virtual,Amritsar,,,0,2026-01-23,...,0,,Active,0.0,NaT,,,,0.0,Active
4464,SBI,10020410,Bimal Tanti,Assam,Sivsagar,Golaghat,,,0,2026-01-23,...,0,,Active,0.0,NaT,,,,0.0,
4465,SBI,10022629,Ajmot Ali,Assam,Dhubri,Kokrajhar,,,0,2026-01-23,...,0,,Active,0.0,NaT,,,,0.0,
4466,BOB,11711238,Mahendra Kumar,Uttar Pradesh,Virtual,Kaushambi,,,0,2026-01-22,...,0,,Active,0.0,NaT,,,,0.0,Active
4467,PNB,K3800763,Kirpal Singh,Jammu And Kashmir,Virtual,Udhampur,,,0,2026-01-21,...,0,,Active,0.0,NaT,,,,0.0,Active

# Removing Cancelled & TBA from csp_master

In [16]:
csp_master_df_1 = csp_master_df[~csp_master_df['CSPCODE'].isin(['Cancelled', 'TBA'])]

In [17]:
csp_master_df_1 = csp_master_df_1.drop_duplicates()

In [18]:
csp_master_df_1.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['BANK', 'CSPCODE', 'CSP_Name', 'Key', 'State', 'Territory', 'District',
       'BLOCK', 'bhk_block_code', 'Status', 'Branch', 'PINCODE',
       'Code_Creation_Date', 'Agreement_Date', 'Agreement_Renewal_Date',
       'IIBF_Certificate_Number', 'Printer', 'MATM', 'PinPad',
       'Licence_Fee_Amount', 'MR_Date', 'MR_No', 'Received_Amount',
       'Vatika_ID', 'Vatika_Name', 'MATM_PINPAD', 'GPS_Dongle',
       'Refund_Amount', 'Licence_Fee_Refund_Date', 'Employee_Mapped', 'Gender',
       'Location_Type', 'Tenure', 'Productive_Status'],
      dtype='object')>

In [38]:
# set(csp_df.columns) - set(csp_master_df.columns)

In [19]:
csp_1 = pd.merge(csp_df, csp_master_df_1, left_on='CSPCODE', right_on = 'CSPCODE', how='left')

# csp_1 = csp_df.merge(csp_master_df_1,on="CSPCODE",how="left",suffixes=("", "_master"))

In [40]:
# csp_1['CSPCODE'].count()
more_than_1 = csp_1.groupby(['CSPCODE'])['CSPCODE'].agg(['count']).sort_values('count', ascending=False).reset_index()[csp_1.groupby(['CSPCODE'])['CSPCODE'].agg(['count']).sort_values('count', ascending=False).reset_index()['count'] > 1]

In [41]:
more_than_1

         CSPCODE  count
0   10022144 (R)     64
1   10022394 (R)     64
2       K3800744     64
3   10022485 (R)     64
4   10022005 (R)     64
5   10022577 (R)     64
6   10022835 (R)     64
7   10022591 (R)     64
8   10022403 (R)     64
9   10022206 (R)     64
10  10022267 (R)     64
11  10022131 (R)     64
12     Cancelled     47
13           TBA     28

In [22]:
csp_1.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['BANK_x', 'CSPCODE', 'CSP Name', 'State_x', 'Territory_x', 'District_x',
       'BLOCK_x', 'Branch_x', 'PINCODE_x', 'Code Creation Date',
       'Agreement Date', 'Agreement Renewal Date', 'IIBF Certificate\nNumber',
       'Printer_x', 'MATM/PINPAD', 'GPS-Dongle', 'Licence Fee\n Amount',
       'MR Date', 'MR No.', 'Received Amount', 'Vatika ID', 'Vatika Name',
       'Status_x', 'Refund Amount', 'Licence_Fee_Refund_Date_x',
       'Employee\nMapped', 'Gender_x', 'Location Type', 'Tenure_x',
       'Productive\nStatus', 'BANK_y', 'CSP_Name', 'Key', 'State_y',
       'Territory_y', 'District_y', 'BLOCK_y', 'bhk_block_code', 'Status_y',
       'Branch_y', 'PINCODE_y', 'Code_Creation_Date', 'Agreement_Date',
       'Agreement_Renewal_Date', 'IIBF_Certificate_Number', 'Printer_y',
       'MATM', 'PinPad', 'Licence_Fee_Amount', 'MR_Date', 'MR_No',
       'Received_Amount', 'Vatika_ID', 'Vatika_Name', 'MATM_PINPAD',
       'GPS_Dongle', 'Refund_Amount', 'Licence_Fee_Refund_Date_y',
       'Employee_Mapped', 'Gender_y', 'Location_Type', 'Tenure_y',
       'Productive_Status'],
      dtype='object')>

In [26]:
csp_df['Refund Amount'].unique()

array([    0.,  8200., 11800., 12000., 20000.])

In [28]:
csp_1 = csp_1[['BANK_x', 'CSPCODE', 'CSP Name', 'State_x', 'Territory_x', 'District_x',
       'BLOCK_x', 'bhk_block_code', 'Status_x', 'Branch_x', 'PINCODE_x', 'Code Creation Date',
       'Agreement Date', 'Agreement Renewal Date', 'IIBF Certificate\nNumber',
       'Printer_x', 'Licence Fee\n Amount', 'MR Date',
       'MR No.', 'Received Amount', 'Vatika ID', 'Vatika Name','Key','Refund Amount', 'Licence_Fee_Refund_Date_x',
       'Employee\nMapped', 'Gender_x', 'Location Type', 'Tenure_x',
       'Productive\nStatus','MATM/PINPAD', 'GPS-Dongle']]

# Renaming Columns

In [29]:
csp_1 = csp_1.rename(columns={
    'BANK_x' : 'BANK',
    'CSP Name': 'CSP_Name',
    'State_x': 'State',
    'Territory_x': 'Territory',
    'District_x': 'District',
    'BLOCK_x': 'BLOCK',
    'Branch_x': 'Branch',
    'PINCODE_x': 'PINCODE',
    'Code Creation Date': 'Code_Creation_Date',
    'Agreement Date': 'Agreement_Date',
    'Agreement Renewal Date': 'Agreement_Renewal_Date',
    'IIBF Certificate\nNumber': 'IIBF_Certificate_Number',
    'Printer_x': 'Printer',
    'MATM_x': 'MATM',
    'PinPad_x': 'PinPad',
    'Licence Fee\n Amount': 'Licence_Fee_Amount',
    'MR Date': 'MR_Date',
    'MR No.': 'MR_No',
    'Received Amount': 'Received_Amount',
    'Vatika ID': 'Vatika_ID',
    'Vatika Name': 'Vatika_Name',
    'Status_x': 'Status',
    'Refund Amount': 'Refund_Amount',
    'Licence_Fee_Refund_Date_x': 'Licence_Fee_Refund_Date',
    'Employee\nMapped': 'Employee_Mapped', 
    'Gender_x': 'Gender', 
    'Location Type': 'Location_Type', 
    'Tenure_x': 'Tenure',
    'Productive\nStatus': 'Productive_Status',
    'MATM/PINPAD': 'MATM_PINPAD', 
    'GPS-Dongle': 'GPS_Dongle'
    # Any extra columns (Refund Amount, Employee Mapped etc.) will remain
})

In [34]:
csp_1['bhk_block_code'] = csp_1['bhk_block_code'].fillna(0)
csp_1['bhk_block_code'] = csp_1['bhk_block_code'].astype(int)
csp_1['Code_Creation_Date'].fillna('1999-01-01', inplace=True)
csp_1['Agreement_Date'].fillna('1999-01-01', inplace=True)
csp_1['Agreement_Renewal_Date'].fillna('1999-01-01', inplace=True)
csp_1['MR_Date'].fillna('1999-01-01', inplace=True)
csp_1['Key'].fillna('', inplace=True)
csp_1['Licence_Fee_Refund_Date'].fillna('1999-01-01', inplace=True)

C:\Users\handa\AppData\Local\Temp\ipykernel_26672\309987720.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csp_1['Code_Creation_Date'].fillna('1999-01-01', inplace=True)
C:\Users\handa\AppData\Local\Temp\ipykernel_26672\309987720.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csp_1['Agreement_Date'].fillna('1999-01-01', inplace=True)
C:\Users\handa\AppData\Local\Temp\ipykernel_26672\309987720.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csp_1['Agreement_Renewal_Date'].fillna('1999-01-01', inplace=True)
C:\Users\handa\AppData\Local\Temp\ipykernel_26672\309987720.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csp_1['MR_Date'].fillna('1999-01-01', inplace=True)
C:\Users\handa\AppData\Local\Temp\ipykernel_26672\309987720.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csp_1['Key'].fillna('', inplace=True)
C:\Users\handa\AppData\Local\Temp\ipykernel_26672\309987720.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csp_1['Licence_Fee_Refund_Date'].fillna('1999-01-01', inplace=True)

In [1]:
# warehouse_cursor.execute("TRUNCATE TABLE WAVE..CSP_Master")

conn.commit()

NameError: name 'conn' is not defined

In [ ]:
csp_1 = csp_1.drop_duplicates()

In [31]:
warehouse_cursor.execute("SELECT * FROM WAVE..CSP_Master")
rows_tuple = [tuple(i) for i in warehouse_cursor.fetchall()]
column = [column[0] for column in warehouse_cursor.description]
csp_master_df_check = pd.DataFrame(rows_tuple, columns=column)

if len(csp_master_df_check) == 0:
    print(f"CSP_Master Truncated...! {len(csp_master_df_check)} Records Found")

CSP_Master Truncated...! 0 Records Found

In [35]:
csp_1

,BANK,CSPCODE,CSP_Name,State,Territory,District,BLOCK,bhk_block_code,Status,Branch,...,Key,Refund_Amount,Licence_Fee_Refund_Date,Employee_Mapped,Gender,Location_Type,Tenure,Productive_Status,MATM_PINPAD,GPS_Dongle
0,BOB,11710778,Jitesh Agrawal,Dadra And Nagar Haveli,Virtual Terr_Dadra And Nagar Haveli,Dadra And Nagar Haveli,Silvassa,0,Active,Silvassa Vapi Mail Road,...,,0.0,1999-01-01,Rahul Sain,M,URBAN,4.0,Active,Available - Working,
1,BOB,11710813,Mahla Monalikumari Gulabbhai,Dadra And Nagar Haveli,Virtual Terr_Dadra And Nagar Haveli,Dadra And Nagar Haveli,Dadarand Nagar Haveli,0,Replacement,Kilavani,...,,0.0,1999-01-01,Rahul Sain,M,RURAL,4.0,,,
2,BOB,11710694,Abhinavkumar Rushabhkumar Yagnik,Gujarat,Virtual Terr_Gujarat,Ahmadabad,Vastral,0,Replacement,"Naroda Road, Ahmedabad",...,,0.0,1999-01-01,,M,,3.9,,,
3,BOB,11710706,Divyaben Nepubhai Makwana,Gujarat,Virtual Terr_Gujarat,Ahmadabad,bavla,0,Replacement,Bavla,...,,0.0,1999-01-01,,F,,3.9,,,
4,BOB,11710652,Mohasinbhai Ishakbhai Chandi,Gujarat,Virtual Terr_Gujarat,Ahmadabad,Ghanchiwada,0,Active,Meghraj,...,,0.0,1999-01-01,Rahul Sain,M,URBAN,4.0,Active,Available - Working,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4499,PNB,K3800727,Ramandeep Kaur,Punjab,Virtual,Amritsar,,0,Active,,...,,0.0,1999-01-01,,,,0.0,Active,Not Available,
4500,SBI,10020410,Bimal Tanti,Assam,Sivsagar,Golaghat,,0,Active,,...,,0.0,1999-01-01,,,,0.0,,,
4501,SBI,10022629,Ajmot Ali,Assam,Dhubri,Kokrajhar,,0,Active,,...,,0.0,1999-01-01,,,,0.0,,Available - Not Working,
4502,BOB,11711238,Mahendra Kumar,Uttar Pradesh,Virtual,Kaushambi,,0,Active,,...,,0.0,1999-01-01,,,,0.0,Active,,
4503,PNB,K3800763,Kirpal Singh,Jammu And Kashmir,Virtual,Udhampur,,0,Active,,...,,0.0,1999-01-01,,,,0.0,Active,,

In [ ]:
table_name = "CSP_Master"  # Replace with your actual table name
batch_size = 1000
idf = csp_1

try:
    columns = idf.columns.tolist()
    # columns_str = ', '.join(columns)
    columns_str = ', '.join([f'[{col}]' for col in columns])
    placeholders = ', '.join(['?' for _ in range(len(columns))])
    insert_query = f"INSERT INTO WAVE..{table_name} ({columns_str}) VALUES ({placeholders})"
    
    total_inserted = 0
    
    # Process in batches
    for i in range(0, len(idf), batch_size):
        batch = idf.iloc[i: i + batch_size]
        records = [tuple(row) for _, row in batch.iterrows()]
        
        print(f"Executing batch insert for records {i} to {i + len(records) - 1}")
        warehouse_cursor.executemany(insert_query, records)
        
        total_inserted += len(records) 
        print(f"Inserted batch: {total_inserted}/{len(idf)} records")
              
    
    print(f"✓ Successfully inserted all {total_inserted} records into {table_name}")
    conn.commit()
    conn.close()
    
except Exception as e:
    # conn.rollback()
    print(f"✗ Error inserting data: {str(e)}")
    
# finally:
#     warehouse_cursor.close()
#     conn.close()

Executing batch insert for records 0 to 999

# WAVE Data

In [6]:
wave_sheet = gc.open_by_url('https://docs.google.com/spreadsheets/d/1SKgKmXeInkKkhEB4eIj0bEBMXel-fvYEnqe4n7OE1hc/edit?usp=sharing')

wave_sheet.worksheets()

PermissionError:

# DataFrames

In [23]:
wave_sheet_1 = wave_sheet.worksheet('Sheet1')

wave_sheet_df = pd.DataFrame(wave_sheet_1.get_all_records())

wave_sheet_df

,Wave,Update,State,Territory,Cluster,Block,Block Status,Vatika,Employee Name,Activity,Target_Date,Remarks,Identify,Expected Date,Complete_Date,BlockId,Id
0,0,2025-12-03,Assam,Dhubri,Barpeta,Chakchaka,New,Not Applicable,Without Employee,CSP Potential,2025-07-31,,,,,2492,2
1,0,2025-12-03,Assam,Dhubri,Barpeta,Chakchaka,New,Not Applicable,Without Employee,Dhavak Onboard,2025-07-31,,,,,2492,3
2,0,2025-12-03,Assam,Dhubri,Barpeta,Chakchaka,New,Not Applicable,Without Employee,Distributor Identify,2025-07-31,,,2025-07-31,,2492,4
3,0,2025-12-03,Assam,Dhubri,Barpeta,Chakchaka,New,Not Applicable,Without Employee,Product Survey,2025-07-31,,,,,2492,5
4,0,2025-12-03,Assam,Dhubri,Barpeta,Chakchaka,New,Not Applicable,Without Employee,Route Mapping,2025-07-31,,,,,2492,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5250,1,2025-12-03,Maharashtra,Nagpur,Wardha,Seloo,Existing,Mahabala,Priyanka Nagtode,Workshop 1A,2025-11-30,,1,,2025-11-02,4610,
5251,1,2025-12-03,Maharashtra,Nagpur,Wardha,Seloo,Existing,Mahabala,Priyanka Nagtode,FGD Complete,2025-09-30,,13,,2025-11-02,4610,
5252,1,2025-12-03,Maharashtra,Nagpur,Wardha,Seloo,Existing,Vadgaon,Priyanka Nagtode,FGD Complete,2025-09-30,,9,,2025-11-20,4610,
5253,0,2025-12-03,West Bengal,Durgapur,Bankura,Taldangra,New,Not Applicable,Kerim Pahalowan,Stock Point,,Not yet,,20-09-2025,2025-12-04,2794,
5254,0,2025-12-03,West Bengal,Kolkata,South 24 Parganas,Canning-I,New,Not Applicable,Supriya Halder,Volunteer Identify,,,3,,2025-11-30,2753,

In [24]:
warehouse_cursor.execute("SELECT * FROM WAVE..[Wave_Progress_2]")

rows_tuple = [tuple(i) for i in warehouse_cursor.fetchall()]
column = [column[0] for column in warehouse_cursor.description]
wave_progress_df = pd.DataFrame(rows_tuple, columns=column)
wave_progress_df

,Wave,Update,State,Territory,Cluster,Block,BlockId,Block_Status,Vatika,Employee_Name,Activity,Target_Date,Remarks,Identify,Expected_Date,Complete_Date,Block_Key,insert_on
0,0,2025-11-06,Assam,Dhubri,Barpeta,Chakchaka,2492,New,Not Applicable,Without Employee,CSP Potential,2025-07-31,None,None,NaT,NaT,None,None
1,0,2025-11-06,Assam,Dhubri,Barpeta,Chakchaka,2492,New,Not Applicable,Without Employee,Dhavak Onboard,2025-07-31,None,None,NaT,NaT,None,None
2,0,2025-11-06,Assam,Dhubri,Barpeta,Chakchaka,2492,New,Not Applicable,Without Employee,Distributor Identify,2025-07-31,None,None,2025-07-31,NaT,None,None
3,0,2025-11-06,Assam,Dhubri,Barpeta,Chakchaka,2492,New,Not Applicable,Without Employee,Product Survey,2025-07-31,None,None,NaT,NaT,None,None
4,0,2025-11-06,Assam,Dhubri,Barpeta,Chakchaka,2492,New,Not Applicable,Without Employee,Route Mapping,2025-07-31,None,None,NaT,NaT,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5130,0,2025-11-06,West Bengal,Durgapur,Purba bardhaman,Memari,0,Existing,Not Applicable,Dhiraj Gupta,Product Survey,NaT,Done,None,2025-09-07,2025-11-03,None,None
5131,0,2025-11-06,West Bengal,Darjeeling,Cooch Behar,Tufanganj 2,0,Existing,Not Applicable,Ashika Oraon,Volunteer Identify,NaT,Done,None,NaT,2025-11-05,None,None
5132,1,2025-11-06,Assam,Sonitpur,Biswanath,Sootea,2715,Existing,Niz-Sootea,Bashab Das,Workshop 1B,2025-09-06,None,None,NaT,2025-11-06,None,None
5133,1,2025-11-06,Assam,Sonitpur,Sonitpur,Gabhoru,2710,Existing,Bhitor Porua,Sabita Biswas,Workshop 1B,2025-09-06,None,None,NaT,2025-11-06,None,None
5134,1,2025-11-06,Assam,Sonitpur,Sonitpur,Gabhoru,2710,Existing,Borguri,Sabita Biswas,Workshop 1B,2025-09-06,None,None,NaT,2025-11-06,None,None

In [25]:
wave_progress_df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['Wave', 'Update', 'State', 'Territory', 'Cluster', 'Block', 'BlockId',
       'Block_Status', 'Vatika', 'Employee_Name', 'Activity', 'Target_Date',
       'Remarks', 'Identify', 'Expected_Date', 'Complete_Date', 'Block_Key',
       'insert_on'],
      dtype='object')>

In [26]:
wave_sheet_df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['Wave', 'Update', 'State', 'Territory', 'Cluster', 'Block',
       'Block Status', 'Vatika', 'Employee Name', 'Activity', 'Target_Date',
       'Remarks', 'Identify', 'Expected Date', 'Complete_Date', 'BlockId',
       'Id'],
      dtype='object')>

# BHK BLock Master

In [27]:
prod_server = os.environ.get("DB2_HOST")
prod_user = os.environ.get("DB2_USER")     
prod_pass = os.environ.get("DB2_PASS")
prod_db = os.environ.get("DB2_NAME")

conn_prod = pyodbc.connect(
            f"Driver={{ODBC Driver 17 for SQL Server}};"
            f"Server={prod_server};"
            f"Database={prod_db};"
            f"UID={prod_user};"
            f"PWD={prod_pass};"
        )
prod_cursor = conn_prod.cursor()
prod_cursor.fast_executemany = True

In [28]:
prod_cursor.execute('''
SELECT bl.block_code , bl.block_name , d.district_code , d.district_name , 
tr.territory_name, st.state_code, st.state_name
FROM [Drishtee_stats_new2024].[dbo].[tbl_block_master] bl
LEFT JOIN [Drishtee_stats_new2024].[dbo].[tbl_district_master] d ON d.district_code = bl.district_code
LEFT JOIN [Drishtee_stats_new2024].[dbo].tbl_territory_master tr ON d.territory_code = tr.territory_code
LEFT JOIN [Drishtee_stats_new2024].[dbo].[tbl_state_master] st ON st.state_code = d.state_code
                    ''')

rows_tuple = [tuple(i) for i in prod_cursor.fetchall()]
column = [column[0] for column in prod_cursor.description]
block_df = pd.DataFrame(rows_tuple, columns=column)
block_df

,block_code,block_name,district_code,district_name,territory_name,state_code,state_name
0,1,Achabal,1,Anantnag,None,1,Jammu And Kashmir
1,2,Breng,1,Anantnag,None,1,Jammu And Kashmir
2,3,Dachnipora,1,Anantnag,None,1,Jammu And Kashmir
3,4,Devsar,622,Kulgam,None,1,Jammu And Kashmir
4,5,D.H. Pora,622,Kulgam,None,1,Jammu And Kashmir
...,...,...,...,...,...,...,...
7299,1116535,Udainagar,402,Dewas,Madhya Pradesh Virtual,23,Madhya Pradesh
7300,1116983,Jharda,435,Ujjain,Madhya Pradesh Virtual,23,Madhya Pradesh
7301,1116995,Makdon,435,Ujjain,Madhya Pradesh Virtual,23,Madhya Pradesh
7302,1117032,Rampura,419,Neemuch,Madhya Pradesh Virtual,23,Madhya Pradesh
7303,1117033,Asansol,704,Paschim Bardhaman,Durgapur,19,West Bengal

# Checking Blocks

In [ ]:
# wave_sheet_df[['State', 'Cluster', 'Block']].drop_duplicates().reset_index(drop=True).to_excel('wave_blocks.xlsx', index=False)

In [32]:
wave_block_df = pd.merge(wave_sheet_df , 
    block_df, left_on=['State', 'Cluster', 'Block'], right_on=['state_name', 'district_name', 'block_name'], how='left'
)

wave_block_df

,Wave,Update,State,Territory,Cluster,Block,Block Status,Vatika,Employee Name,Activity,...,Complete_Date,BlockId,Id,block_code,block_name,district_code,district_name,territory_name,state_code,state_name
0,0,2025-12-03,Assam,Dhubri,Barpeta,Chakchaka,New,Not Applicable,Without Employee,CSP Potential,...,,2492,2,2492.0,Chakchaka,280.0,Barpeta,Dhubri,18.0,Assam
1,0,2025-12-03,Assam,Dhubri,Barpeta,Chakchaka,New,Not Applicable,Without Employee,Dhavak Onboard,...,,2492,3,2492.0,Chakchaka,280.0,Barpeta,Dhubri,18.0,Assam
2,0,2025-12-03,Assam,Dhubri,Barpeta,Chakchaka,New,Not Applicable,Without Employee,Distributor Identify,...,,2492,4,2492.0,Chakchaka,280.0,Barpeta,Dhubri,18.0,Assam
3,0,2025-12-03,Assam,Dhubri,Barpeta,Chakchaka,New,Not Applicable,Without Employee,Product Survey,...,,2492,5,2492.0,Chakchaka,280.0,Barpeta,Dhubri,18.0,Assam
4,0,2025-12-03,Assam,Dhubri,Barpeta,Chakchaka,New,Not Applicable,Without Employee,Route Mapping,...,,2492,6,2492.0,Chakchaka,280.0,Barpeta,Dhubri,18.0,Assam
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5250,1,2025-12-03,Maharashtra,Nagpur,Wardha,Seloo,Existing,Mahabala,Priyanka Nagtode,Workshop 1A,...,2025-11-02,4610,,4610.0,Seloo,498.0,Wardha,Nagpur,27.0,Maharashtra
5251,1,2025-12-03,Maharashtra,Nagpur,Wardha,Seloo,Existing,Mahabala,Priyanka Nagtode,FGD Complete,...,2025-11-02,4610,,4610.0,Seloo,498.0,Wardha,Nagpur,27.0,Maharashtra
5252,1,2025-12-03,Maharashtra,Nagpur,Wardha,Seloo,Existing,Vadgaon,Priyanka Nagtode,FGD Complete,...,2025-11-20,4610,,4610.0,Seloo,498.0,Wardha,Nagpur,27.0,Maharashtra
5253,0,2025-12-03,West Bengal,Durgapur,Bankura,Taldangra,New,Not Applicable,Kerim Pahalowan,Stock Point,...,2025-12-04,2794,,2794.0,Taldangra,305.0,Bankura,Durgapur,19.0,West Bengal
5254,0,2025-12-03,West Bengal,Kolkata,South 24 Parganas,Canning-I,New,Not Applicable,Supriya Halder,Volunteer Identify,...,2025-11-30,2753,,2753.0,Canning-I,304.0,South 24 Parganas,Kolkatta,19.0,West Bengal

In [34]:
wave_block_df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['Wave', 'Update', 'State', 'Territory', 'Cluster', 'Block',
       'Block Status', 'Vatika', 'Employee Name', 'Activity', 'Target_Date',
       'Remarks', 'Identify', 'Expected Date', 'Complete_Date', 'BlockId',
       'Id', 'block_code', 'block_name', 'district_code', 'district_name',
       'territory_name', 'state_code', 'state_name'],
      dtype='object')>

# Finalizing Data

In [42]:
wave_block_df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['Wave', 'Update', 'State', 'Territory', 'Cluster', 'Block',
       'Block Status', 'Vatika', 'Employee Name', 'Activity', 'Target_Date',
       'Remarks', 'Identify', 'Expected Date', 'Complete_Date', 'BlockId',
       'Id', 'block_code', 'block_name', 'district_code', 'district_name',
       'territory_name', 'state_code', 'state_name'],
      dtype='object')>

In [40]:
wave_progress_df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['Wave', 'Update', 'State', 'Territory', 'Cluster', 'Block', 'BlockId',
       'Block_Status', 'Vatika', 'Employee_Name', 'Activity', 'Target_Date',
       'Remarks', 'Identify', 'Expected_Date', 'Complete_Date', 'Block_Key',
       'insert_on'],
      dtype='object')>

In [ ]:
wave_block_df = wave_block_df[['Wave', 'Update', 'State', 'Territory', 'Cluster', 'Block','block_code',
       'Block Status', 'Vatika', 'Employee Name', 'Activity', 'Target_Date',
       'Remarks', 'Identify', 'Expected Date', 'Complete_Date']]

# Rename Columns

In [46]:
wave_block_df.rename(columns={
    'block_code' : 'BlockId',
    'Block Status' : 'Block_Status',
    'Employee Name' : 'Employee_Name',
    'Expected Date' : 'Expected_Date',
}, inplace=True)

C:\Users\handa\AppData\Local\Temp\ipykernel_24204\3345037734.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wave_block_df.rename(columns={

In [53]:
wave_block_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5255 entries, 0 to 5254
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Wave           5255 non-null   int64
 1   Update         5255 non-null   datetime64[ns]
 2   State          5255 non-null   object
 3   Territory      5255 non-null   object
 4   Cluster        5255 non-null   object
 5   Block          5255 non-null   object
 6   BlockId        5255 non-null   int32
 7   Block_Status   5255 non-null   object
 8   Vatika         5255 non-null   object
 9   Employee_Name  5255 non-null   object
 10  Activity       5255 non-null   object
 11  Target_Date    4571 non-null   datetime64[ns]
 12  Remarks        5255 non-null   object
 13  Identify       5255 non-null   object
 14  Expected_Date  2501 non-null   datetime64[ns]
 15  Complete_Date  2291 non-null   datetime64[ns]
dtypes: datetime64[ns](4), int32(1), int64(1), object(10)
memory usage: 636.5+ KB

In [57]:
wave_block_df[:1]

,Wave,Update,State,Territory,Cluster,Block,BlockId,Block_Status,Vatika,Employee_Name,Activity,Target_Date,Remarks,Identify,Expected_Date,Complete_Date
0,0,2025-12-03,Assam,Dhubri,Barpeta,Chakchaka,2492,New,Not Applicable,Without Employee,CSP Potential,2025-07-31,,,NaT,NaT

# Datatypes

In [ ]:
wave_block_df['Update'] = pd.to_datetime(wave_block_df['Update'])
wave_block_df['Target_Date'] = pd.to_datetime(wave_block_df['Target_Date'], errors='coerce')
wave_block_df['Expected_Date'] = pd.to_datetime(wave_block_df['Expected_Date'],errors='coerce')
wave_block_df['Complete_Date'] = pd.to_datetime(wave_block_df['Complete_Date'], errors='coerce')
wave_block_df['BlockId'] = pd.to_numeric(wave_block_df['BlockId'], errors='coerce').fillna(0).astype('int')

C:\Users\handa\AppData\Local\Temp\ipykernel_24204\895532070.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wave_block_df['BlockId'] = pd.to_numeric(wave_block_df['BlockId'], errors='coerce').fillna(0).astype('int')

In [ ]:
wave_block_df['Expected_Date'] = wave_block_df['Expected_Date'].fillna(pd.Timestamp('1999-01-01'))
wave_block_df['Complete_Date'] = wave_block_df['Complete_Date'].fillna(pd.Timestamp('1999-01-01'))
wave_block_df['Target_Date'] = wave_block_df['Target_Date'].fillna(pd.Timestamp('1999-01-01'))
wave_block_df['Update'] = wave_block_df['Target_Date'].fillna(pd.Timestamp('1999-01-01'))

C:\Users\handa\AppData\Local\Temp\ipykernel_24204\800360026.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wave_block_df['Update'] = wave_block_df['Target_Date'].fillna(pd.Timestamp('1999-01-01'))

In [119]:
l = ['Update','Target_Date','Expected_Date', 'Complete_Date']

for i in l:
    print(f"{i}: {wave_block_df[i].unique()}\n")

Update: <DatetimeArray>
['2025-07-31 00:00:00', '2025-09-30 00:00:00', '2025-03-31 00:00:00',
 '2025-08-31 00:00:00', '2025-09-06 00:00:00', '2025-06-30 00:00:00',
 '2025-03-02 00:00:00', '2025-02-01 00:00:00', '2025-02-04 00:00:00',
 '2025-02-08 00:00:00',
 ...
 '2026-03-30 00:00:00', '2025-10-20 00:00:00', '2025-12-20 00:00:00',
 '2025-11-07 00:00:00', '2025-11-30 00:00:00', '2025-12-30 00:00:00',
 '2025-10-15 00:00:00', '2025-12-12 00:00:00', '2025-11-06 00:00:00',
 '2025-11-25 00:00:00']
Length: 102, dtype: datetime64[ns]

Target_Date: <DatetimeArray>
['2025-07-31 00:00:00', '2025-09-30 00:00:00', '2025-03-31 00:00:00',
 '2025-08-31 00:00:00', '2025-09-06 00:00:00', '2025-06-30 00:00:00',
 '2025-03-02 00:00:00', '2025-02-01 00:00:00', '2025-02-04 00:00:00',
 '2025-02-08 00:00:00',
 ...
 '2026-03-30 00:00:00', '2025-10-20 00:00:00', '2025-12-20 00:00:00',
 '2025-11-07 00:00:00', '2025-11-30 00:00:00', '2025-12-30 00:00:00',
 '2025-10-15 00:00:00', '2025-12-12 00:00:00', '2025-11-06 00:00:00',
 '2025-11-25 00:00:00']
Length: 102, dtype: datetime64[ns]

Expected_Date: <DatetimeArray>
['1999-01-01 00:00:00', '2025-07-31 00:00:00', '2025-09-30 00:00:00',
 '2025-03-31 00:00:00', '2025-08-31 00:00:00', '2025-01-10 00:00:00',
 '2025-01-07 00:00:00', '2024-12-30 00:00:00', '2025-01-25 00:00:00',
 '2025-01-27 00:00:00',
 ...
 '2025-07-18 00:00:00', '2024-11-12 00:00:00', '2025-06-24 00:00:00',
 '2025-10-22 00:00:00', '2025-10-17 00:00:00', '2025-09-22 00:00:00',
 '2025-09-18 00:00:00', '2025-11-15 00:00:00', '2025-11-17 00:00:00',
 '2025-04-11 00:00:00']
Length: 196, dtype: datetime64[ns]

Complete_Date: <DatetimeArray>
['1999-01-01 00:00:00', '2025-11-19 00:00:00', '2024-10-12 00:00:00',
 '2025-01-23 00:00:00', '2025-02-20 00:00:00', '2025-01-19 00:00:00',
 '2025-10-11 00:00:00', '2025-03-02 00:00:00', '2025-11-18 00:00:00',
 '2025-11-21 00:00:00',
 ...
 '2024-09-12 00:00:00', '2025-07-19 00:00:00', '2024-11-15 00:00:00',
 '2025-11-14 00:00:00', '2025-11-12 00:00:00', '2025-10-02 00:00:00',
 '2025-04-11 00:00:00', '2025-05-11 00:00:00', '2025-11-23 00:00:00',
 '2025-12-04 00:00:00']
Length: 420, dtype: datetime64[ns]

# Adding Remaining Columns

In [ ]:
wave_block_df['Block_Key'] = wave_block_df['State'] + ' ' + wave_block_df['Cluster'] + ' ' + wave_block_df['Block']
wave_block_df['insert_on'] = pd.to_datetime(datetime.now().date())

# Taking Backup

In [ ]:
backup = warehouse_cursor.execute('''
                        USE WAVE
                                  
                        TRUNCATE TABLE  Wave_backup
                                  
                        INSERT INTO Wave_backup
                        SELECT [Wave]
                            ,[Update]
                            ,[State]
                            ,[Territory]
                            ,[Cluster]
                            ,[Block]
                            ,[BlockId]
                            ,[Block_Status]
                            ,[Vatika]
                            ,[Employee_Name]
                            ,[Activity]
                            ,[Target_Date]
                            ,[Remarks]
                            ,[Identify]
                            ,[Expected_Date]
                            ,[Complete_Date]
                            ,[Block_Key] 
                            FROM Wave_Progress_2
                                  
                        TRUNCATE TABLE  Wave_Progress_2
                         ''')
conn.commit()

if backup:
    print("Wave_Progress_2 Backup Created Successfully...!")

Wave_Progress_2 Backup Created Successfully...!

In [121]:
table_name = "Wave_Progress_2"  
data = wave_block_df
batch_size = 1000   
bulk_insert(table_name,data, batch_size)

Executing batch insert for records 0 to 999
Inserted batch: 1000/5255 records
Executing batch insert for records 1000 to 1999
Inserted batch: 2000/5255 records
Executing batch insert for records 2000 to 2999
Inserted batch: 3000/5255 records
Executing batch insert for records 3000 to 3999
Inserted batch: 4000/5255 records
Executing batch insert for records 4000 to 4999
Inserted batch: 5000/5255 records
Executing batch insert for records 5000 to 5254
Inserted batch: 5255/5255 records
✓ Successfully inserted all 5255 records into Wave_Progress_2

In [ ]:
# final_df[['State', 'Cluster', 'Block', 'block_code']].drop_duplicates().to_excel('wave_blocks_with_codes.xlsx', index=False)

# CSP Commission

In [38]:
csp_comm_sheet = gc.open_by_url('https://docs.google.com/spreadsheets/d/1r7u4fBEp5gU-4wtcQayBGQynJ4onWA76mM62eQA-7Rc/edit?usp=sharing')

csp_comm_sheet.worksheets()

In [36]:
comm_sheet_df = pd.DataFrame(csp_comm_sheet.worksheet('Sheet1').get_all_records())
comm_sheet_df

,Comm_Month,Accounting_Month,Bank,CSP_Code,State,Territorry,District,Comm_Pena,Revenue_Category,Revenue_Head,Count,Comm,Tag,Last Update
0,2026-04-30,2026-05-31,SBI,10021602,West Bengal,,Darjeeling,Comm,Withdrawal,AEPS ONUS WITHDRAWAL,680,7592.5,LM,20-May-2026
1,2026-04-30,2026-05-31,SBI,10021602,West Bengal,,Darjeeling,Comm,Fund Transfer,MONEY TRANSFER,73,658.5,LM,20-May-2026
2,2026-04-30,2026-05-31,SBI,10021602,West Bengal,,Darjeeling,Comm,Deposit,CASH DEPOSIT,1,2.0,LM,20-May-2026
3,2026-04-30,2026-05-31,SBI,10021602,West Bengal,,Darjeeling,Comm,Deposit,AEPS ONUS DEPOSIT,39,349.13,LM,20-May-2026
4,2026-04-30,2026-05-31,SBI,10021602,West Bengal,,Darjeeling,Comm,Investment,RD OPEN,1,10.0,LM,20-May-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32840,2026-04-30,2026-05-31,BOM,12320049,West Bengal,,North 24 Parganas,Comm,Withdrawal,Final Eligible Txn,352,3702.2,LM,20-May-2026
32841,2026-04-30,2026-05-31,BOM,12320049,West Bengal,,North 24 Parganas,Comm,Social Security Scheme & A/C Opening,No_of Funded Accounts,39,975.0,LM,20-May-2026
32842,2026-04-30,2026-05-31,BOM,12320049,West Bengal,,North 24 Parganas,Comm,Social Security Scheme & A/C Opening,PMSBY,15,15.0,LM,20-May-2026
32843,2026-04-30,2026-05-31,BOM,12320051,Odisha,,Bhadrak,Comm,Withdrawal,Final Eligible Txn,95,809.4,LM,20-May-2026
32844,2026-04-30,2026-05-31,BOM,12320054,West Bengal,,Dakshin Dinajpur,Comm,Withdrawal,Final Eligible Txn,3,6.0,LM,20-May-2026

# tmp_csp_commission

In [39]:
prod_cursor.execute("SELECT TOP(1000) * FROM WAVE..tmp_csp_commission ORDER BY id DESC")

rows_tuple = [tuple(i) for i in prod_cursor.fetchall()]

column = [column[0] for column in prod_cursor.description]

tmp_csp_commission_df = pd.DataFrame(rows_tuple, columns=column)
tmp_csp_commission_df

,Comm_Month,Accounting_Month,Bank,CSP_Code,State,Territorry,District,Comm_Pena,Revenue_Category,Revenue_Head,Count,Comm,Tag,imported_by,imported_at,is_processed,id,error_in_process
0,2026-04-30,2026-05-31,BOM,12320054,West Bengal,,Dakshin Dinajpur,Comm,Withdrawal,Final Eligible Txn,3.0000000000,6.0000000000,LM,DF1002,2026-05-27 13:28:53,1,2397295,0
1,2026-04-30,2026-05-31,BOM,12320051,Odisha,,Bhadrak,Comm,Withdrawal,Final Eligible Txn,95.0000000000,809.4000000000,LM,DF1002,2026-05-27 13:28:53,1,2397294,0
2,2026-04-30,2026-05-31,BOM,12320049,West Bengal,,North 24 Parganas,Comm,Social Security Scheme & A/C Opening,PMSBY,15.0000000000,15.0000000000,LM,DF1002,2026-05-27 13:28:53,1,2397293,0
3,2026-04-30,2026-05-31,BOM,12320049,West Bengal,,North 24 Parganas,Comm,Social Security Scheme & A/C Opening,No_of Funded Accounts,39.0000000000,975.0000000000,LM,DF1002,2026-05-27 13:28:53,1,2397292,0
4,2026-04-30,2026-05-31,BOM,12320049,West Bengal,,North 24 Parganas,Comm,Withdrawal,Final Eligible Txn,352.0000000000,3702.2000000000,LM,DF1002,2026-05-27 13:28:53,1,2397291,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2026-04-30,2026-05-31,UBI,UBI4100070,Karnataka,,Ramanagara,Comm,Non Transactional,MINI_STATEMENT,1233.0000000000,204.0000000000,LM,DF1002,2026-05-27 13:28:53,1,2396300,0
996,2026-04-30,2026-05-31,UBI,UBI4100070,Karnataka,,Ramanagara,Comm,Investment,FD,4.0000000000,20.0000000000,LM,DF1002,2026-05-27 13:28:53,1,2396299,0
997,2026-04-30,2026-05-31,UBI,UBI4100070,Karnataka,,Ramanagara,Comm,Social Security Scheme & A/C Opening,EKYC,4.0000000000,40.0000000000,LM,DF1002,2026-05-27 13:28:53,1,2396298,0
998,2026-04-30,2026-05-31,UBI,UBI4100070,Karnataka,,Ramanagara,Comm,Other Commission,CBC_FIXED,0E-10,2500.0000000000,LM,DF1002,2026-05-27 13:28:53,1,2396297,0
999,2026-04-30,2026-05-31,UBI,UBI4100070,Karnataka,,Ramanagara,Comm,Other Commission,BC_FIXED,0E-10,2250.0000000000,LM,DF1002,2026-05-27 13:28:53,1,2396296,0

# CSP_log

In [37]:
prod_cursor.execute("SELECT TOP(1000) * FROM WAVE..COMMISSION_Update_log")

rows_tuple = [tuple(i) for i in prod_cursor.fetchall()]

column = [column[0] for column in prod_cursor.description]

commission_log_df = pd.DataFrame(rows_tuple, columns=column)
commission_log_df

  last_update_date      table_name             inserted_on
0       2025-12-16  CSP_Commission                     NaT
1       2026-01-19  CSP_Commission                     NaT
2       2026-01-19  CSP_Commission                     NaT
3       2026-01-30  CSP_Commission                     NaT
4       2026-02-10  CSP_Commission 2026-03-05 13:36:42.160
5       2026-03-19  CSP_Commission 2026-03-30 00:00:00.000
6       2026-04-16  CSP_Commission 2026-05-27 13:24:01.000

In [12]:
comm_sheet_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35373 entries, 0 to 35372
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Comm_Month        35373 non-null  object
 1   Accounting_Month  35373 non-null  object
 2   Bank              35373 non-null  object
 3   CSP_Code          35373 non-null  object
 4   State             35373 non-null  object
 5   Territorry        35373 non-null  object
 6   District          35373 non-null  object
 7   Comm_Pena         35373 non-null  object
 8   Revenue_Category  35373 non-null  object
 9   Revenue_Head      35373 non-null  object
 10  Count             35373 non-null  object
 11  Comm              35373 non-null  object
 12  Tag               35373 non-null  object
 13  Last Update       35373 non-null  object
dtypes: object(14)
memory usage: 3.8+ MB

# Transformation

In [ ]:
comm_sheet_df['Comm_Month'] = pd.to_datetime(comm_sheet_df['Comm_Month'])
comm_sheet_df['Accounting_Month'] = pd.to_datetime(comm_sheet_df['Accounting_Month'])
comm_sheet_df['Last Update'] = pd.to_datetime(comm_sheet_df['Last Update'])
comm_sheet_df['Comm'] = pd.to_numeric(comm_sheet_df['Comm'], errors='coerce').fillna(0).astype('float')
comm_sheet_df['Count'] = pd.to_numeric(comm_sheet_df['Count'], errors='coerce').fillna(0).astype('int')

In [ ]:
comm_sheet_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35373 entries, 0 to 35372
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Comm_Month        35373 non-null  datetime64[ns]
 1   Accounting_Month  35373 non-null  datetime64[ns]
 2   Bank              35373 non-null  object
 3   CSP_Code          35373 non-null  object
 4   State             35373 non-null  object
 5   Territorry        35373 non-null  object
 6   District          35373 non-null  object
 7   Comm_Pena         35373 non-null  object
 8   Revenue_Category  35373 non-null  object
 9   Revenue_Head      35373 non-null  object
 10  Count             35373 non-null  int32
 11  Comm              35373 non-null  float64
 12  Tag               35373 non-null  object
 13  Last Update       35373 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(1), int32(1), object(9)
memory usage: 3.6+ MB

In [77]:
comm_sheet_df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['Comm_Month', 'Accounting_Month', 'Bank', 'CSP_Code', 'State',
       'Territorry', 'District', 'Comm_Pena', 'Revenue_Category',
       'Revenue_Head', 'Count', 'Comm', 'Tag', 'Last Update'],
      dtype='object')>

In [78]:
tmp_csp_commission_df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['Comm_Month', 'Accounting_Month', 'Bank', 'CSP_Code', 'State',
       'Territorry', 'District', 'Comm_Pena', 'Revenue_Category',
       'Revenue_Head', 'Count', 'Comm', 'Tag', 'imported_by', 'imported_at',
       'is_processed', 'id', 'error_in_process'],
      dtype='object')>

In [ ]:
datetime.now().strftime('%Y-%m-%d %H:%M:%S')

'2026-05-27 13:22:26.000'

# Filtering csp_comm_sheet

In [17]:
mx_1 = commission_log_df[commission_log_df['table_name'] == 'CSP_Commission']
mx_1['last_update_date'].max()

datetime.date(2026, 3, 19)

In [18]:
pd.to_datetime(mx_1['last_update_date'].max()),comm_sheet_df['Last Update'].unique()

(Timestamp('2026-03-19 00:00:00'),
 <DatetimeArray>
 ['2026-04-14 00:00:00', '2026-04-16 00:00:00']
 Length: 2, dtype: datetime64[ns])

In [19]:
comm_sheet_df_1 = comm_sheet_df[comm_sheet_df['Last Update'] > pd.to_datetime(mx_1['last_update_date'].max().strftime('%Y-%m-%d'))]
comm_sheet_df_1

,Comm_Month,Accounting_Month,Bank,CSP_Code,State,Territorry,District,Comm_Pena,Revenue_Category,Revenue_Head,Count,Comm,Tag,Last Update
0,2026-03-31,2026-04-30,SBI,10021602,West Bengal,,Darjeeling,Comm,Incentive,AVERAGE BALANCE MAINTENANCE,4734,18315.06,LM,2026-04-14
1,2026-03-31,2026-04-30,SBI,10021602,West Bengal,,Darjeeling,Comm,Withdrawal,AEPS ONUS WITHDRAWAL,594,6472.00,LM,2026-04-14
2,2026-03-31,2026-04-30,SBI,10021602,West Bengal,,Darjeeling,Comm,Incentive,RURAL COMMISSION,0,2000.00,LM,2026-04-14
3,2026-03-31,2026-04-30,SBI,10021602,West Bengal,,Darjeeling,Comm,Fund Transfer,MONEY TRANSFER,81,705.00,LM,2026-04-14
4,2026-03-31,2026-04-30,SBI,10021602,West Bengal,,Darjeeling,Comm,Deposit,CASH DEPOSIT,2,7.50,LM,2026-04-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35368,2026-03-31,2026-04-30,PNB,K3800787,Assam,,Karimganj,Comm,Social Security Scheme & A/C Opening,PMJJBY,9,67.50,LM,2026-04-16
35369,2026-03-31,2026-04-30,PNB,K3800787,Assam,,Karimganj,Comm,Social Security Scheme & A/C Opening,PMSBY,1,1.00,LM,2026-04-16
35370,2026-03-31,2026-04-30,PNB,K3800787,Assam,,Karimganj,Comm,Non Transactional,SMS_EML_STMT,2,10.00,LM,2026-04-16
35371,2026-03-31,2026-04-30,PNB,K3800787,Assam,,Karimganj,Comm,Deposit,TPD,2,1.80,LM,2026-04-16
35372,2026-03-31,2026-04-30,PNB,K3800787,Assam,,Karimganj,Comm,Non Transactional,UID_SEEDING,8,40.00,LM,2026-04-16

In [20]:
comm_sheet_df_1['imported_by'] = 'DF1002'
comm_sheet_df_1['imported_at'] = pd.to_datetime(datetime.now().strftime('%Y-%m-%d %H:%M:%S')) 
comm_sheet_df_1['is_processed'] = 0
comm_sheet_df_1['error_in_process'] = 0

In [21]:
comm_sheet_df_1 = comm_sheet_df_1[['Comm_Month', 'Accounting_Month', 'Bank', 'CSP_Code', 'State',
       'Territorry', 'District', 'Comm_Pena', 'Revenue_Category',
       'Revenue_Head', 'Count', 'Comm', 'Tag', 'imported_by', 'imported_at',
       'is_processed', 'error_in_process']]

# Insert into tmp_csp_comm

In [25]:
table_name = "tmp_csp_commission"  # Replace with your actual table name
batch_size = 1000
idf = comm_sheet_df_1

bulk_insert(table_name, idf, batch_size, prod_cursor)

Executing batch insert for records 0 to 999
Inserted batch: 1000/35373 records
Executing batch insert for records 1000 to 1999
Inserted batch: 2000/35373 records
Executing batch insert for records 2000 to 2999
Inserted batch: 3000/35373 records
Executing batch insert for records 3000 to 3999
Inserted batch: 4000/35373 records
Executing batch insert for records 4000 to 4999
Inserted batch: 5000/35373 records
Executing batch insert for records 5000 to 5999
Inserted batch: 6000/35373 records
Executing batch insert for records 6000 to 6999
Inserted batch: 7000/35373 records
Executing batch insert for records 7000 to 7999
Inserted batch: 8000/35373 records
Executing batch insert for records 8000 to 8999
Inserted batch: 9000/35373 records
Executing batch insert for records 9000 to 9999
Inserted batch: 10000/35373 records
Executing batch insert for records 10000 to 10999
Inserted batch: 11000/35373 records
Executing batch insert for records 11000 to 11999
Inserted batch: 12000/35373 records
Executing batch insert for records 12000 to 12999
Inserted batch: 13000/35373 records
Executing batch insert for records 13000 to 13999
Inserted batch: 14000/35373 records
Executing batch insert for records 14000 to 14999
Inserted batch: 15000/35373 records
Executing batch insert for records 15000 to 15999
Inserted batch: 16000/35373 records
Executing batch insert for records 16000 to 16999
Inserted batch: 17000/35373 records
Executing batch insert for records 17000 to 17999
Inserted batch: 18000/35373 records
Executing batch insert for records 18000 to 18999
Inserted batch: 19000/35373 records
Executing batch insert for records 19000 to 19999
Inserted batch: 20000/35373 records
Executing batch insert for records 20000 to 20999
Inserted batch: 21000/35373 records
Executing batch insert for records 21000 to 21999
Inserted batch: 22000/35373 records
Executing batch insert for records 22000 to 22999
Inserted batch: 23000/35373 records
Executing batch insert for records 23000 to 23999
Inserted batch: 24000/35373 records
Executing batch insert for records 24000 to 24999
Inserted batch: 25000/35373 records
Executing batch insert for records 25000 to 25999
Inserted batch: 26000/35373 records
Executing batch insert for records 26000 to 26999
Inserted batch: 27000/35373 records
Executing batch insert for records 27000 to 27999
Inserted batch: 28000/35373 records
Executing batch insert for records 28000 to 28999
Inserted batch: 29000/35373 records
Executing batch insert for records 29000 to 29999
Inserted batch: 30000/35373 records
Executing batch insert for records 30000 to 30999
Inserted batch: 31000/35373 records
Executing batch insert for records 31000 to 31999
Inserted batch: 32000/35373 records
Executing batch insert for records 32000 to 32999
Inserted batch: 33000/35373 records
Executing batch insert for records 33000 to 33999
Inserted batch: 34000/35373 records
Executing batch insert for records 34000 to 34999
Inserted batch: 35000/35373 records
Executing batch insert for records 35000 to 35372
Inserted batch: 35373/35373 records
✓ Successfully inserted all 35373 records into tmp_csp_commission

# Insert_into_CSP_Commission

In [26]:
insert_date = datetime.now().strftime('%Y-%m-%d')
prod_cursor.execute(f'''
                         USE WAVE;
                         exec sp_Insert_into_CSP_Commission '{insert_date}'
                         ''')
prod_cursor.connection.commit()

# Insert Into COMMISSION_Update_log

In [ ]:
commission_log_df = pd.DataFrame([{
    "last_update_date": comm_sheet_df['Last Update'].max(),
    "table_name": "CSP_Commission",
    "inserted_on": datetime.now().strftime('%Y-%m-%d %H:%M:%S')
}])
commission_log_df

  last_update_date      table_name          inserted_on
0       2026-05-20  CSP_Commission  2026-05-27 13:33:26

In [41]:
table_name = "COMMISSION_Update_log"  # Replace with your actual table name
batch_size = 1000
idf = commission_log_df

bulk_insert(table_name, idf, batch_size , prod_cursor)

Executing batch insert for records 0 to 0
Inserted batch: 1/1 records
✓ Successfully inserted all 1 records into COMMISSION_Update_log

# RFS

In [5]:
rfs_sheet_url = 'https://docs.google.com/spreadsheets/d/1FilWyVH4o0k_VnGOgfTVIGTgRX1iQgDY/edit?gid=597382910#gid=597382910'
# This is a non Google Doc inspite uploaded Excel File in Google drive. So we will use Google Drive API to download the file and then read it using pandas.

In [6]:
# Creating drive service to access Google Drive API
drive = build( "drive", "v3", credentials=creds)

# Id
rfs_file_id = "1FilWyVH4o0k_VnGOgfTVIGTgRX1iQgDY"

# Verifying Drive can see the file.
file = drive.files().get(fileId=rfs_file_id,fields="id,name,mimeType").execute()

file

{'id': '1FilWyVH4o0k_VnGOgfTVIGTgRX1iQgDY',
 'name': 'RFS Dashboard WF 22 June.xlsx',
 'mimeType': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}

In [7]:
# Download the Excel File into Memory 
# Instead of saving the file to disk, we'll download it into RAM (BytesIO).

# Create a request to download the file
request = drive.files().get_media(fileId=rfs_file_id)

# Create an in-memory binary stream
excel_stream = io.BytesIO()

# Download the file
downloader = MediaIoBaseDownload(excel_stream, request)

done = False

while not done:
    status, done = downloader.next_chunk()
    print(f"Downloaded: {int(status.progress() * 100)}%")

# Move pointer back to the beginning
excel_stream.seek(0)

print("Download Completed Successfully!")

Downloaded: 100%
Download Completed Successfully!

# Borrower Details

In [12]:
# Now we can read the Excel file from the in-memory stream using pandas.
rfs_sheet = pd.ExcelFile(excel_stream)
# print(rfs_sheet.sheet_names)
rfs_master = pd.read_excel(rfs_sheet, sheet_name='Borrower Details') 
rfs_master

,Sr._No.,Grantor,Borrower_Category,Year,Month,State,Territory,District,Actual_Block,BHK_block,...,RFS_Due_Date,Repayment,Correct_Repayment_Date_Format,Correct_RFS_Date_Format,discrepancy_in_repayble_amount,Remarks,PAN_Card_Details (for vaibhavi group it will be group PAN card & for other borrowers they need to provide individual),Guarantor_Details,No._of_Producers_Connected,Case_Study
0,1.0,DDCL,Vaibhavi-DRISHTEE,2024.0,March,West Bengal,Kolkata,South 24 Parganas,Bhangar-II,2748.0,...,NaN,Closed,NaN,2024-03-21,Extra Amount :- 1186,"Initial 2 months interest part to be paid i,e ...",Yes,NaN,NaN,NaN
1,2.0,DF,Vaibhavi-DRISHTEE,2024.0,June,Bihar,Bhagalpur,Bhagalpur,Thrithala,NaN,...,NaN,Closed,NaN,2024-06-18,Extra Amount :- 27144,Initial 4 months total interest part to be pai...,Yes,NaN,NaN,NaN
2,3.0,DF,Vaibhavi-DRISHTEE,2022.0,January,Bihar,Madhubani,Bhagalpur,Thrithala,NaN,...,NaN,Closed,NaN,2022-01-04,NaN,NaN,Yes,NaN,NaN,NaN
3,4.0,DDCL,Vaibhavi-DRISHTEE,2022.0,December,Bihar,Madhubani,Bhagalpur,Thrithala,NaN,...,NaN,Closed,NaN,2022-12-17,Extra Amount :- 5868,"Initial 2 months interest part to be paid i,e ...",Yes,NaN,NaN,NaN
4,5.0,DDCL,Vaibhavi-DRISHTEE,2023.0,October,Bihar,Madhubani,Bhagalpur,Thrithala,NaN,...,NaN,Closed,NaN,2023-05-10,Extra Amount :- 22770,NaN,Yes,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,NaN,RANGDE,CSP-RANGDE,2026.0,NaN,Assam,NaN,Dhubri,NaN,NaN,...,NaN,On track,NaN,2026-08-03,NaN,NaN,NaN,NaN,NaN,NaN
976,NaN,RANGDE,CSP-RANGDE,2026.0,NaN,Assam,NaN,Golaghat,NaN,NaN,...,NaN,On track,NaN,2026-08-03,NaN,NaN,NaN,NaN,NaN,NaN
977,NaN,RANGDE,CSP-RANGDE,2026.0,NaN,Assam,NaN,Dhubri,NaN,NaN,...,NaN,On track,NaN,2026-08-03,NaN,NaN,NaN,NaN,NaN,NaN
978,NaN,RANGDE,CSP-RANGDE,2026.0,NaN,Assam,NaN,Cachar,NaN,NaN,...,NaN,On track,NaN,2026-08-03,NaN,NaN,NaN,NaN,NaN,NaN
979,NaN,RANGDE,CSP-RANGDE,2026.0,NaN,Assam,NaN,Cachar,NaN,NaN,...,NaN,On track,NaN,2026-08-03,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
rfs_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 38 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Sr._No.                            970 non-null    int64
 1   Grantor                            970 non-null    object
 2   Borrower_Category                  970 non-null    object
 3   Year                               970 non-null    int32
 4   Month                              57 non-null     object
 5   State                              969 non-null    object
 6   Territory                          162 non-null    object
 7   District                           968 non-null    object
 8   Actual_Block                       114 non-null    object
 9   BHK_block                          667 non-null    float64
 10  Vatika                             275 non-null    object
 11  Responsible_field_Person           929 non-null    object
 12  Contact_Numbar                     253 non-null    object
 13  Borrower_Name                      970 non-null    object
 14  Contact_Numbar.1                   245 non-null    float64
 15  Group_Members                      942 non-null    float64
 16  Vaibhavi_ID_(For_Rangde-Loan_ID)   966 non-null    float64
 17  Value_Chain                        969 non-null    object
 18  RFS_Agreement                      0 non-null      float64
 19  RFS_Date                           836 non-null    object
 20  Tenure_(in_months)                 933 non-null    object
 21  RFS_Grantor                        970 non-null    object
 22  RFS_Amt                            970 non-null    int64
 23  Admin_charges                      876 non-null    float64
 24  Total_Repayable_Amount             899 non-null    float64
 25  Total_Repaid_Amount                844 non-null    float64
 26  Total_Outstanding_Amount           871 non-null    float64
 27  Monthly_Scheduled_EMI              762 non-null    object
 28  RFS_Status                         970 non-null    object
 29  EMI_Received_for_the_recent_month  32 non-null     float64
 30  Total_Amount_Overdue               830 non-null    float64
 31  Repayment_Report                   60 non-null     object
 32  Latest_Date_of_Repayment           228 non-null    object
 33  NA                                 47 non-null     datetime64[ns]
 34  DPD                                206 non-null    float64
 35  Repayment                          964 non-null    object
 36  Correct_Repayment_Date_Format      228 non-null    object
 37  Correct_RFS_Date_Format            836 non-null    object
dtypes: datetime64[ns](1), float64(12), int32(1), int64(2), object(22)
memory usage: 284.3+ KB

In [65]:
rfs_master.columns

Index(['Sr._No.', 'Grantor', 'Borrower_Category', 'Year', 'Month', 'State',
       'Territory', 'District', 'Actual_Block', 'BHK_block', 'Vatika',
       'Responsible_field_Person', 'Contact_Numbar', 'Borrower_Name',
       'Contact_Numbar.1', 'Group_Members', 'Vaibhavi_ID_(For_Rangde-Loan_ID)',
       'Value_Chain', 'RFS_Agreement', 'RFS_Date', 'Tenure_(in_months)',
       'RFS_Grantor', 'RFS_Amt', 'Admin_charges', 'Total_Repayable_Amount',
       'Total_Repaid_Amount', 'Total_Outstanding_Amount',
       'Monthly_Scheduled_EMI', 'RFS_Status',
       'EMI_Received_for_the_recent_month', 'Total_Amount_Overdue',
       'Repayment_Report', 'Latest_Date_of_Repayment', 'NA', 'DPD',
       'Repayment', 'Correct_Repayment_Date_Format',
       'Correct_RFS_Date_Format'],
      dtype='object')

In [11]:
# rfs_master['Year'] = pd.to_numeric(rfs_master['Year'], errors='coerce').fillna(0).astype('int')
# rfs_master.info()
rfs_master['Contact_Numbar.1'].unique()

array([          0, -2147483648])

# Datatype Corrections

In [7]:
date_cols = [
    "RFS_Date",
    "Latest_Date_of_Repayment",
    "Correct_Repayment_Date_Format",
    "Correct_RFS_Date_Format",
    "NA"
]

numeric_cols = [
    "Sr._No.",
    "Year",
    "Group_Members",
    "Tenure_(in_months)",
    "DPD",
    "BHK_block",
    "Vaibhavi_ID_(For_Rangde-Loan_ID)"
]

float_cols = [
    "RFS_Amt",
    "Admin_charges",
    "Total_Repayable_Amount",
    "Total_Repaid_Amount",
    "Total_Outstanding_Amount",
    "Monthly_Scheduled_EMI",
    "EMI_Received_for_the_recent_month",
    "Total_Amount_Overdue"
]

string_cols = [
    "Grantor",
    "Borrower_Category",
    "Month",
    "State",
    "Territory",
    "District",
    "Actual_Block",
    "Vatika",
    "Responsible_field_Person",
    "Contact_Numbar",
    "Contact_Numbar.1",
    "Borrower_Name",
    "Value_Chain",
    "RFS_Agreement",
    "RFS_Grantor",
    "RFS_Status",
    "Repayment_Report",
    "Repayment"
]

# Dates
for col in date_cols:
    if col in rfs_master.columns:
        rfs_master[col] = pd.to_datetime(rfs_master[col], errors="coerce")

# Numbers
for col in numeric_cols:
    if col in rfs_master.columns:
        rfs_master[col] = pd.to_numeric(rfs_master[col], errors="coerce").fillna(0).astype('int')

# floats
for col in float_cols:
    if col in rfs_master.columns:
        rfs_master[col] = pd.to_numeric(rfs_master[col], errors="coerce").fillna(0.0).astype('float')

# Strings
for col in string_cols:
    if col in rfs_master.columns:
        rfs_master[col] = rfs_master[col].fillna('').astype("string")

# csp_df['PINCODE'] = pd.to_numeric(csp_df['PINCODE'], errors='coerce').fillna(0).astype('int')
# # csp_df['MATM'] = pd.to_numeric(csp_df['MATM'], errors='coerce').fillna(0).astype('int')
# # csp_df['PinPad'] = pd.to_numeric(csp_df['PinPad'], errors='coerce').fillna(0).astype('int')
# csp_df['Vatika ID'] = pd.to_numeric(csp_df['Vatika ID'], errors='coerce').fillna(0).astype('int')
# csp_df['MR No.'] = pd.to_numeric(csp_df['MR No.'], errors='coerce').fillna(0).astype('int')
# csp_df['Licence Fee\n Amount'] = pd.to_numeric(csp_df['Licence Fee\n Amount'], errors='coerce').fillna(0.0)
# csp_df['Received Amount'] = pd.to_numeric(csp_df['Received Amount'], errors='coerce').fillna(0.0)
# csp_df['Refund Amount'] = pd.to_numeric(csp_df['Refund Amount'], errors='coerce').fillna(0.0)
# csp_df['Tenure'] = pd.to_numeric(csp_df['Tenure'], errors='coerce').fillna(0.0)

In [9]:
rfs_master.columns , rfs_master[rfs_master['Sr._No.'] == 299].values

(Index(['Sr._No.', 'Grantor', 'Borrower_Category', 'Year', 'Month', 'State',
        'Territory', 'District', 'Actual_Block', 'BHK_block', 'Vatika',
        'Responsible_field_Person', 'Contact_Numbar', 'Borrower_Name',
        'Contact_Numbar.1', 'Group_Members', 'Vaibhavi_ID_(For_Rangde-Loan_ID)',
        'Value_Chain', 'RFS_Agreement', 'RFS_Date', 'Tenure_(in_months)',
        'RFS_Grantor', 'RFS_Amt', 'Admin_charges', 'Total_Repayable_Amount',
        'Total_Repaid_Amount', 'Total_Outstanding_Amount',
        'Monthly_Scheduled_EMI', 'RFS_Status',
        'EMI_Received_for_the_recent_month', 'Total_Amount_Overdue',
        'Repayment_Report', 'Latest_Date_of_Repayment', 'NA', 'DPD',
        'Repayment', 'Correct_Repayment_Date_Format',
        'Correct_RFS_Date_Format'],
       dtype='object'),
 array([[299, 'RANGDE', 'RANGDE Vaibhavi', 2025, '', 'Assam', '', 'Hojai',
         'Udali', 2675, '1 No Kaki', 'Rubel', '7576892966',
         'Nitumoni Devi', -2147483648, 1, 37322,
         'Textile & Textile Based', '', Timestamp('2026-01-16 00:00:00'),
         12, 'RANGDE', 15000.0, 1351.85, 16351.85, 6815.0, 9536.85, 0.0,
         'Upcoming', 0.0, 0.0, '', Timestamp('2026-07-07 00:00:00'), NaT,
         0, 'On track', Timestamp('2026-07-07 00:00:00'),
         Timestamp('2026-01-16 00:00:00')]], dtype=object))

In [ ]:
rfs_master_2 = rfs_master.astype(object)
rfs_master_2 = rfs_master_2.where(pd.notnull(rfs_master), None)
# rfs_master_2['Correct_RFS_Date_Format'].unique()

array([Timestamp('2024-03-21 00:00:00'), Timestamp('2024-06-18 00:00:00'),
       Timestamp('2022-01-04 00:00:00'), Timestamp('2022-12-17 00:00:00'),
       Timestamp('2023-05-10 00:00:00'), Timestamp('2025-06-26 00:00:00'),
       Timestamp('2024-08-18 00:00:00'), Timestamp('2024-09-27 00:00:00'),
       Timestamp('2023-12-19 00:00:00'), Timestamp('2024-05-18 00:00:00'),
       Timestamp('2023-01-11 00:00:00'), Timestamp('2022-01-10 00:00:00'),
       Timestamp('2024-11-01 00:00:00'), Timestamp('2023-11-12 00:00:00'),
       Timestamp('2021-12-24 00:00:00'), Timestamp('2022-03-28 00:00:00'),
       Timestamp('2024-02-15 00:00:00'), Timestamp('2022-03-16 00:00:00'),
       Timestamp('2024-01-30 00:00:00'), Timestamp('2022-05-18 00:00:00'),
       Timestamp('2023-07-24 00:00:00'), Timestamp('2024-03-22 00:00:00'),
       Timestamp('2023-10-25 00:00:00'), Timestamp('2024-03-26 00:00:00'),
       Timestamp('2023-12-22 00:00:00'), Timestamp('2024-06-19 00:00:00'),
       Timestamp('2023-08-30 00:00:00'), Timestamp('2024-01-20 00:00:00'),
       Timestamp('2023-02-16 00:00:00'), Timestamp('2023-12-26 00:00:00'),
       Timestamp('2021-12-31 00:00:00'), Timestamp('2024-05-15 00:00:00'),
       Timestamp('2025-12-13 00:00:00'), Timestamp('2022-02-14 00:00:00'),
       Timestamp('2024-05-20 00:00:00'), Timestamp('2025-05-29 00:00:00'),
       Timestamp('2022-01-06 00:00:00'), Timestamp('2023-06-10 00:00:00'),
       Timestamp('2025-03-27 00:00:00'), Timestamp('2025-12-17 00:00:00'),
       Timestamp('2023-12-29 00:00:00'), Timestamp('2024-01-23 00:00:00'),
       Timestamp('2022-01-11 00:00:00'), Timestamp('2022-10-01 00:00:00'),
       Timestamp('2023-12-17 00:00:00'), Timestamp('2025-05-05 00:00:00'),
       Timestamp('2025-10-30 00:00:00'), None,
       Timestamp('2024-09-30 00:00:00'), Timestamp('2024-12-16 00:00:00'),
       Timestamp('2025-02-05 00:00:00'), Timestamp('2025-02-06 00:00:00'),
       Timestamp('2025-06-16 00:00:00'), Timestamp('2025-02-07 00:00:00'),
       Timestamp('2025-07-17 00:00:00'), Timestamp('2025-07-16 00:00:00'),
       Timestamp('2025-04-08 00:00:00'), Timestamp('2025-02-09 00:00:00'),
       Timestamp('2025-09-16 00:00:00'), Timestamp('2025-03-10 00:00:00'),
       Timestamp('2025-03-11 00:00:00'), Timestamp('2025-11-18 00:00:00'),
       Timestamp('2025-11-17 00:00:00'), Timestamp('2025-02-12 00:00:00'),
       Timestamp('2026-01-16 00:00:00'), Timestamp('2026-02-02 00:00:00'),
       Timestamp('2026-03-02 00:00:00'), Timestamp('2026-03-16 00:00:00'),
       Timestamp('2026-02-03 00:00:00'), Timestamp('2023-10-14 00:00:00'),
       Timestamp('2023-12-31 00:00:00'), Timestamp('2024-02-16 00:00:00'),
       Timestamp('2024-03-18 00:00:00'), Timestamp('2024-02-13 00:00:00'),
       Timestamp('2024-09-25 00:00:00'), Timestamp('2024-08-29 00:00:00'),
       Timestamp('2023-11-01 00:00:00'), Timestamp('2023-12-21 00:00:00'),
       Timestamp('2024-06-21 00:00:00'), Timestamp('2024-07-01 00:00:00'),
       Timestamp('2024-01-31 00:00:00'), Timestamp('2024-05-31 00:00:00'),
       Timestamp('2024-04-30 00:00:00'), Timestamp('2024-08-31 00:00:00'),
       Timestamp('2024-07-31 00:00:00'), Timestamp('2024-12-31 00:00:00'),
       Timestamp('2026-03-17 00:00:00'), Timestamp('2026-03-31 00:00:00'),
       Timestamp('2026-04-16 00:00:00'), Timestamp('2026-05-18 00:00:00'),
       Timestamp('2026-02-06 00:00:00'), Timestamp('2026-06-16 00:00:00'),
       Timestamp('2026-07-02 00:00:00'), Timestamp('2026-07-04 00:00:00')],
      dtype=object)

In [14]:
# for i in rfs_master_2.columns:
#     print(i, " -> " , rfs_master_2[i].unique())

In [11]:
rfs_master_2.to_excel("rfs_master.xlsx", index = False)

In [13]:
rfs_master_2 = rfs_master_2[['Sr._No.', 'Grantor', 'Borrower_Category', 'Year', 'Month', 'State',
       'Territory', 'District', 'Actual_Block', 'BHK_block', 'Vatika',
       'Responsible_field_Person', 'Contact_Numbar', 'Borrower_Name',
       'Contact_Numbar.1', 'Group_Members', 'Vaibhavi_ID_(For_Rangde-Loan_ID)',
       'Value_Chain', 'RFS_Agreement', 'RFS_Date', 'Tenure_(in_months)',
       'RFS_Grantor', 'RFS_Amt', 'Admin_charges', 'Total_Repayable_Amount',
       'Total_Repaid_Amount', 'Total_Outstanding_Amount',
       'Monthly_Scheduled_EMI', 'RFS_Status',
       'EMI_Received_for_the_recent_month', 'Total_Amount_Overdue',
       'Repayment_Report', 'Latest_Date_of_Repayment', 'DPD',
       'Repayment', 'Correct_Repayment_Date_Format',
       'Correct_RFS_Date_Format']]

In [25]:
rfs_master_2.rename(columns={'Sr._No.': 'Sr_No' , 'Contact_Numbar.1':'Contact_Numbar_1', 'Vaibhavi_ID_(For_Rangde-Loan_ID)': 'Vaibhavi_ID_For_Rangde_Loan_ID', 'Tenure_(in_months)': 'Tenure_in_months'}, inplace=True)

In [21]:
rfs_master_2['inserted_on'] = pd.to_datetime(datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'))

In [26]:
rfs_master_2[:5]

,Sr_No,Grantor,Borrower_Category,Year,Month,State,Territory,District,Actual_Block,BHK_block,...,RFS_Status,EMI_Received_for_the_recent_month,Total_Amount_Overdue,Repayment_Report,Latest_Date_of_Repayment,DPD,Repayment,Correct_Repayment_Date_Format,Correct_RFS_Date_Format,inserted_on
0,1,DDCL,Vaibhavi,2024,March,West Bengal,Kolkata,South 24 Parganas,,0,...,Matured,0.0,0.0,,None,0,Closed,None,2024-03-21 00:00:00,2026-07-14 01:11:05.485031
1,2,DF,Vaibhavi,2024,June,Bihar,Bhagalpur,Bhagalpur,,0,...,Matured,35484.0,0.0,Amyra,2026-07-06 00:00:00,7,delayed,2026-07-06 00:00:00,2024-06-18 00:00:00,2026-07-14 01:11:05.485031
2,3,DF,Vaibhavi,2022,January,Bihar,Madhubani,Bhagalpur,,0,...,Matured,0.0,0.0,,None,0,Closed,None,2022-01-04 00:00:00,2026-07-14 01:11:05.485031
3,4,DDCL,Vaibhavi,2022,December,Bihar,Madhubani,Bhagalpur,,0,...,Matured,0.0,0.0,,None,0,Closed,None,2022-12-17 00:00:00,2026-07-14 01:11:05.485031
4,5,DDCL,Vaibhavi,2023,October,Bihar,Madhubani,Bhagalpur,,0,...,Matured,0.0,0.0,,None,0,Closed,None,2023-05-10 00:00:00,2026-07-14 01:11:05.485031

In [27]:
table_name = "rfs_master"  # Replace with your actual table name
batch_size = 1000
idf = rfs_master_2

bulk_insert(table_name, idf, batch_size, prod_cursor)

Executing batch insert for records 0 to 969
Inserted batch: 970/970 records
✓ Successfully inserted all 970 records into rfs_master

# RFS Producers

In [8]:
# Now we can read the Excel file from the in-memory stream using pandas.
rfs_sheet = pd.ExcelFile(excel_stream)
# print(rfs_sheet.sheet_names)
rfs_producers = pd.read_excel(rfs_sheet, sheet_name='Producer details') 
rfs_producers[:10]

,Sr_NO,State,District,Name_of_the_producer,Contact_No,Associated_with_vaibhavi,VaibhaviId,Working_Since_(in months),vaibhavi_value_chain,helped_the_group_in,...,personal_business/group_business/labour_basis_with_other_groups,livelihood_earning_from_each_value_chain_before_this,livelihood_earning_current_(monthly),Income_Change_(₹),%_Change,Income_Status,Experience_Level,Diversification_Status,_livelihood_options_according_to_them_with_Rs_200_every_day_for_the_entire_year__,Date_of_Collection
0,1,Assam,Darrang,Dipa Deka,NaN,Kalyani Vaibhavi Group,30700,3,goatary,feeding and cleaning goats,...,none,0.0,3000,3000,NaN,Improved,New (3m),Single VC,"piggery,mushroom",2026-08-06
1,2,Assam,sonitpur,Barnali Boro,NaN,Swapna MEG,31228,12,Textile and pickle,"raw fruit cutting and packaging - pickle, fabr...",...,labour basis with other group,4000.0,7000,3000,75.000000,Strong Growth,Experienced,Multi VC,"bakery, piggery",2026-08-06
2,3,Assam,Darrang,Madhabi Kalita,NaN,MN Udyogi Group,28004,4,mushroom,cylindar making,...,labour basis with other group,6000.0,4000,-2000,-33.333333,Declined,Mid,Single VC,animal husbandry,2026-08-06
3,4,Bihar,bhagalpur,Rimmi,NaN,Amyra,10372,12,textile,"stitching, cutting",...,labour basis with other groups,5000.0,6000,1000,20.000000,Moderate Growth,Experienced,Single VC,"shop - grocery, tution",2026-08-06
4,5,Bihar,bhagalpur,kaynath,NaN,Amyra,10372,24,textile,stitching,...,personal business,2000.0,5000,3000,150.000000,Strong Growth,Senior (2 yrs),Single VC,textile,2026-08-06
5,6,Assam,Lakhimpur,Monalisa Doley,NaN,Punasang Aschur Group,4520,1,mushroom,paddy straw cutting and boiling,...,personal business,3000.0,800,-2200,-73.333333,Highly Declined,Very New,Single VC,textile & weaving,2026-08-06
6,7,West Bengal,South 24 PGS,Laboni Ghosh,NaN,Alisha Mahila Group,29257,7,textile,"Hem stitching, alter work",...,none,0.0,3500,3500,NaN,Improved,Mid,Single VC,animal husbandry,2026-08-06
7,8,Bihar,bhagalpur,komal,NaN,Amyra,10372,12,textile,Stitching,...,none,0.0,2000,2000,NaN,Improved,Experienced,Single VC,textile,2026-08-06
8,9,West Bengal,South 24 PGS,Tajmira Bibi,NaN,Ichhepuron group,29185,2,poultry,"cleaning shade, feeder drinker management",...,none,0.0,1200,1200,NaN,Low Improvement,Very New,Single VC,"poultry,textile",2026-08-06
9,10,West Bengal,South 24 pgs,Safia bibi,NaN,Alisha Mahila Group,29257,8,textile,"hem stitching, chain integration",...,none,0.0,4000,4000,NaN,Improved,Mid,Single VC,"nursery, animal husbandry",2026-08-06

In [10]:
rfs_producers.columns

Index(['Sr_NO', 'State', 'District', 'Name_of_the_producer', 'Contact_No',
       'Associated_with_vaibhavi', 'VaibhaviId', 'Working_Since_(in months)',
       'vaibhavi_value_chain', 'helped_the_group_in',
       'worked_on__how_many_value_chains__before_this',
       'name_of_the_value_chains_worked_on_earlier',
       'personal_business/group_business/labour_basis_with_other_groups',
       'livelihood_earning_from_each_value_chain_before_this',
       'livelihood_earning_current_(monthly)', 'Income_Change_(₹)', '%_Change',
       'Income_Status', 'Experience_Level', 'Diversification_Status',
       '_livelihood_options_according_to_them_with_Rs_200_every_day_for_the_entire_year__',
       'Date_of_Collection'],
      dtype='object')

In [11]:
rfs_producers.rename(columns={'livelihood_earning_current_(monthly)':'livelihood_earning_current_monthly','Income_Change_(₹)': 'Income_Change', 'Working_Since_(in months)':'Working_Since_in_months','worked_on__how_many_value_chains__before_this':'worked_on_how_many_value_chains_before_this',
                              'personal_business/group_business/labour_basis_with_other_groups':
                              'persol_business_group_business_labour_basis_with_other_groups',
                              '_livelihood_options_according_to_them_with_Rs_200_every_day_for_the_entire_year__':'livelihood_options_according_to_them_with_Rs_200_every_day_for_the_entire_year'}, inplace=True)

numeric_cols = ['Sr_NO','VaibhaviId','worked_on_how_many_value_chains_before_this']

float_cols = ["Income_Change", 'livelihood_earning_current_monthly','Working_Since_in_months','%_Change',
              'livelihood_earning_from_each_value_chain_before_this']

string_cols = ['State', 'District', 'Name_of_the_producer', 'Contact_No',
       'Associated_with_vaibhavi',
       'vaibhavi_value_chain', 'helped_the_group_in',
       'name_of_the_value_chains_worked_on_earlier',
       'persol_business_group_business_labour_basis_with_other_groups',
       'Income_Status', 'Experience_Level', 'Diversification_Status',
       'livelihood_options_according_to_them_with_Rs_200_every_day_for_the_entire_year'
      ]

# Numbers
for col in numeric_cols:
    if col in rfs_producers.columns:
        rfs_producers[col] = pd.to_numeric(rfs_producers[col], errors="coerce").fillna(0).astype('int')

# floats
for col in float_cols:
    if col in rfs_producers.columns:
        rfs_producers[col] = pd.to_numeric(rfs_producers[col], errors="coerce").fillna(0.0).astype('float')

for col in string_cols:
    if col in rfs_producers.columns:
        rfs_producers[col] = rfs_producers[col].fillna('').astype("string")

In [12]:
rfs_producers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 22 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   Sr_NO                                                                           115 non-null    int32
 1   State                                                                           115 non-null    string
 2   District                                                                        115 non-null    string
 3   Name_of_the_producer                                                            115 non-null    string
 4   Contact_No                                                                      115 non-null    string
 5   Associated_with_vaibhavi                                                        115 non-null    string
 6   VaibhaviId                                                                      115 non-null    int32
 7   Working_Since_in_months                                                         115 non-null    float64
 8   vaibhavi_value_chain                                                            115 non-null    string
 9   helped_the_group_in                                                             115 non-null    string
 10  worked_on_how_many_value_chains_before_this                                     115 non-null    int32
 11  name_of_the_value_chains_worked_on_earlier                                      115 non-null    string
 12  persol_business_group_business_labour_basis_with_other_groups                   115 non-null    string
 13  livelihood_earning_from_each_value_chain_before_this                            115 non-null    float64
 14  livelihood_earning_current_monthly                                              115 non-null    float64
 15  Income_Change                                                                   115 non-null    float64
 16  %_Change                                                                        115 non-null    float64
 17  Income_Status                                                                   115 non-null    string
 18  Experience_Level                                                                115 non-null    string
 19  Diversification_Status                                                          115 non-null    string
 20  livelihood_options_according_to_them_with_Rs_200_every_day_for_the_entire_year  115 non-null    string
 21  Date_of_Collection                                                              115 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int32(3), string(13)
memory usage: 18.5 KB

In [13]:
rfs_producers['inserted_on'] = pd.to_datetime(datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'))

In [14]:
rfs_producers = rfs_producers.replace({pd.NA: None, "nan": None, "NaN": None, "None": None})
rfs_producers = rfs_producers.where(pd.notna(rfs_producers), None)

In [17]:
table_name = "RFS_Producers"  # Replace with your actual table name
batch_size = 1000
idf = rfs_producers

bulk_insert(table_name, idf, batch_size, prod_cursor)

Executing batch insert for records 0 to 114
Inserted batch: 115/115 records
✓ Successfully inserted all 115 records into RFS_Producers